// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"fmt"
	"maps"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func setRestMetadataText(m *api.Method, isAsync bool, requestType string) string {
	context := "rest_context"
	optionsStr := "options"
	if isAsync {
		context = "*rest_context"
		optionsStr = "*options"
	}

	orderedRouting := getOrderedRouting(m)
	if len(orderedRouting) == 0 {
		return fmt.Sprintf("  SetMetadata(%s, %s);", context, optionsStr)
	}

	var sb strings.Builder
	sb.WriteString("  std::vector<std::string> params;\n")
	sb.WriteString("  params.reserve(" + strconv.Itoa(len(orderedRouting)) + ");\n\n")

	for _, r := range orderedRouting {
		allMatchAll := true
		for _, v := range r.Variants {
			if routingVariantPattern(v) != "(.*)" {
				allMatchAll = false
				break
			}
		}

		if allMatchAll {
			sep := "  "
			for _, v := range r.Variants {
				accessor := formatRoutingFieldAccessor(v.FieldPath)
				sb.WriteString(sep)
				sb.WriteString("if (!request." + accessor + "().empty()) {\n")
				sb.WriteString("    params.push_back(absl::StrCat(\"" + r.Name + "=\", internal::UrlEncode(request." + accessor + "())));\n")
				sb.WriteString("  }")
				sep = " else "
			}
			sb.WriteString("\n\n")
			continue
		}

		sb.WriteString("  static auto* " + r.Name + "_matcher = []{\n")
		sb.WriteString("    return new google::cloud::internal::RoutingMatcher<" + requestType + ">{\n")
		sb.WriteString("      \"" + r.Name + "=\", {\n")
		for _, v := range r.Variants {
			accessor := formatRoutingFieldAccessor(v.FieldPath)
			sb.WriteString("      {[](" + requestType + " const& request) -> std::string const& {\n")
			sb.WriteString("        return request." + accessor + "();\n")
			sb.WriteString("      },\n")
			pat := routingVariantPattern(v)
			if pat == "(.*)" {
				sb.WriteString("      absl::nullopt},\n")
			} else {
				sb.WriteString("      std::regex{\"" + pat + "\", std::regex::optimize}},\n")
			}
		}
		sb.WriteString("      }};\n")
		sb.WriteString("  }();\n")
		sb.WriteString("  " + r.Name + "_matcher->AppendParam(request, params);\n\n")
	}

	sb.WriteString("  SetMetadata(" + context + ", " + optionsStr + ", params);\n")
	return sb.String()
}

func generateRestMetadataDecoratorHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["metadata_rest_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_rest_header_path"],
		"google/cloud/future.h",
		"google/cloud/rest_options.h",
		"google/cloud/version.h",
	})

	var protoIncludes []string
	protoIncludes = append(protoIncludes, vars["proto_header_path"])
	if hasLongrunningMethod(methods) {
		protoIncludes = append(protoIncludes, "google/longrunning/operations.pb.h")
	}
	p.ProtobufIncludes(protoIncludes)
	p.SystemIncludes([]string{"memory", "string"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $metadata_rest_class_name$ : public $stub_rest_class_name$ {
 public:
  ~$metadata_rest_class_name$() override = default;
  explicit $metadata_rest_class_name$(
      std::shared_ptr<$stub_rest_class_name$> child,
      std::string api_client_header = "");
`)

	restMethods := getRestMethods(methods)
	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			p.PrintWith(mVars, `
  google::cloud::future<StatusOr<$response_type$>> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;

  StatusOr<$response_type$> $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) override;
`)
		} else {
			p.PrintWith(mVars, `
  $return_type$ $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) override;
`)
		}
	}

	restAsyncMethods := getRestAsyncMethods(asyncMethods)
	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  google::cloud::future<$return_type$> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
  google::cloud::future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::GetOperationRequest const& request) override;

  google::cloud::future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::CancelOperationRequest const& request) override;
`)
	}

	p.Print(`
 private:
  void SetMetadata(rest_internal::RestContext& rest_context,
                   Options const& options,
                   std::vector<std::string> const& params = {});

  std::shared_ptr<$stub_rest_class_name$> child_;
  std::string api_client_header_;
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateRestMetadataDecoratorCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["metadata_rest_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	localIncludes := []string{
		vars["metadata_rest_header_path"],
		"absl/strings/str_format.h",
		"google/cloud/internal/absl_str_cat_quiet.h",
		"google/cloud/internal/api_client_header.h",
		"google/cloud/internal/rest_set_metadata.h",
		"google/cloud/status_or.h",
	}
	if hasExplicitRoutingMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/routing_matcher.h")
	}
	p.CcLocalIncludes(localIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
$metadata_rest_class_name$::$metadata_rest_class_name$(
    std::shared_ptr<$stub_rest_class_name$> child,
    std::string api_client_header)
    : child_(std::move(child)),
      api_client_header_(
          api_client_header.empty()
              ? google::cloud::internal::GeneratedLibClientHeader()
              : std::move(api_client_header)) {}
`)

	restMethods := getRestMethods(methods)
	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			metaAsync := setRestMetadataText(m, true, mVars["request_type"])
			metaSync := setRestMetadataText(m, false, mVars["request_type"])
			p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
$metadata_rest_class_name$::Async$method_name$(
      CompletionQueue& cq,
      std::unique_ptr<rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
`+metaAsync+`
  return child_->Async$method_name$(
      cq, std::move(rest_context), std::move(options), request);
}

StatusOr<$response_type$>
$metadata_rest_class_name$::$method_name$(
    rest_internal::RestContext& rest_context,
    Options const& options, $request_type$ const& request) {
`+metaSync+`
  return child_->$method_name$(rest_context, options, request);
}
`)
		} else {
			metaSync := setRestMetadataText(m, false, mVars["request_type"])
			p.PrintWith(mVars, `
$return_type$
$metadata_rest_class_name$::$method_name$(
    rest_internal::RestContext& rest_context,
    Options const& options, $request_type$ const& request) {
`+metaSync+`
  return child_->$method_name$(rest_context, options, request);
}
`)
		}
	}

	restAsyncMethods := getRestAsyncMethods(asyncMethods)
	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		metaAsync := setRestMetadataText(m, true, mVars["request_type"])
		p.PrintWith(mVars, `
future<$return_type$>
$metadata_rest_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
`+metaAsync+`
  return child_->Async$method_name$(
      cq, std::move(rest_context), std::move(options), request);
}
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
$metadata_rest_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::GetOperationRequest const& request) {
  SetMetadata(*rest_context, *options);
  return child_->AsyncGetOperation(
      cq, std::move(rest_context), std::move(options), request);
}

future<Status>
$metadata_rest_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::CancelOperationRequest const& request) {
  SetMetadata(*rest_context, *options);
  return child_->AsyncCancelOperation(
      cq, std::move(rest_context), std::move(options), request);
}
`)
	}

	p.Print(`
void $metadata_rest_class_name$::SetMetadata(
      rest_internal::RestContext& rest_context,
      Options const& options, std::vector<std::string> const& params) {
`)
	if vars["api_version"] != "" {
		p.Print(`  rest_context.AddHeader("x-goog-api-version", "$api_version$");
`)
	}
	p.Print(`  google::cloud::rest_internal::SetMetadata(
      rest_context, options, params, api_client_header_);
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	return filepath.Clean(ccPath), p.String()
}
