// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"
	"slices"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func getProtoGrpcHeaders(svc *api.Service, serviceVars map[string]string, methods []*api.Method, model *api.API) []string {
	var headers []string
	seen := make(map[string]bool)
	if h := serviceVars["proto_grpc_header_path"]; h != "" {
		seen[h] = true
		headers = append(headers, h)
	}
	for _, m := range methods {
		if m.SourceService != nil && m.SourceService.ID != svc.ID {
			h := ""
			if loc, ok := model.DefinitionLocation(m.SourceService.ID[1:]); ok {
				h = strings.TrimSuffix(loc.Filename, ".proto") + ".grpc.pb.h"
			} else if m.SourceService.ID == ".google.cloud.location.Locations" {
				h = "google/cloud/location/locations.grpc.pb.h"
			}
			if h != "" && !seen[h] {
				seen[h] = true
				headers = append(headers, h)
			}
		}
	}
	slices.Sort(headers)
	return headers
}

func generateIdempotencyPolicyHeader(svc *api.Service, serviceVars map[string]string, methods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["idempotency_policy_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		"google/cloud/idempotency.h",
		"google/cloud/version.h",
	})

	pbHeaders := getProtoGrpcHeaders(svc, serviceVars, methods, model)
	p.ProtobufIncludes(pbHeaders)
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_namespace"])

	p.Print(`
class $idempotency_class_name$ {
 public:
  virtual ~$idempotency_class_name$();

  /// Create a new copy of this object.
  virtual std::unique_ptr<$idempotency_class_name$> clone() const;
`)

	for _, m := range methods {
		if isStreaming(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isPaginated(m) {
			p.PrintWith(mVars, `
  virtual google::cloud::Idempotency
  $method_name$($request_type$ request);
`)
		} else {
			p.PrintWith(mVars, `
  virtual google::cloud::Idempotency
  $method_name$($request_type$ const& request);
`)
		}
	}

	p.Print(`};

std::unique_ptr<$idempotency_class_name$>
    MakeDefault$idempotency_class_name$();
`)

	p.HeaderCloseNamespaces(vars["product_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateIdempotencyPolicyCc(svc *api.Service, serviceVars map[string]string, methods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["idempotency_policy_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{vars["idempotency_policy_header_path"]})
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_namespace"])

	p.Print(`
using ::google::cloud::Idempotency;

$idempotency_class_name$::~$idempotency_class_name$() = default;

std::unique_ptr<$idempotency_class_name$>
$idempotency_class_name$::clone() const {
  return std::make_unique<$idempotency_class_name$>(*this);
}
`)

	for _, m := range methods {
		if isStreaming(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		isSetIam := m.OutputTypeID == ".google.iam.v1.Policy" && m.InputTypeID == ".google.iam.v1.SetIamPolicyRequest"
		if isSetIam {
			p.PrintWith(mVars, `
Idempotency $idempotency_class_name$::$method_name$(
    google::iam::v1::SetIamPolicyRequest const& request) {
  return request.policy().etag().empty() ? Idempotency::kNonIdempotent
                                         : Idempotency::kIdempotent;
}
`)
			continue
		}

		if isPaginated(m) {
			if hasRequestID(m) {
				p.PrintWith(mVars, `
Idempotency $idempotency_class_name$::$method_name$($request_type$ request) { // NOLINT
  if (!request.$request_id_field_name$().empty()) return Idempotency::kIdempotent;
  return Idempotency::$idempotency$;
}
`)
			} else {
				p.PrintWith(mVars, `
Idempotency $idempotency_class_name$::$method_name$($request_type$) {  // NOLINT
  return Idempotency::$idempotency$;
}
`)
			}
			continue
		}

		if hasRequestID(m) {
			p.PrintWith(mVars, `
Idempotency $idempotency_class_name$::$method_name$($request_type$ const& request) {
  if (!request.$request_id_field_name$().empty()) return Idempotency::kIdempotent;
  return Idempotency::$idempotency$;
}
`)
			continue
		}

		p.PrintWith(mVars, `
Idempotency $idempotency_class_name$::$method_name$($request_type$ const&) {
  return Idempotency::$idempotency$;
}
`)
	}

	p.Print(`
std::unique_ptr<$idempotency_class_name$>
    MakeDefault$idempotency_class_name$() {
  return std::make_unique<$idempotency_class_name$>();
}
`)

	p.HeaderCloseNamespaces(vars["product_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
