// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"fmt"
	"maps"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateStubFactoryHeader(_ *api.Service, serviceVars map[string]string, _ *config.Library) (string, string) {
	headerPath := serviceVars["stub_factory_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_header_path"],
		"google/cloud/internal/unified_grpc_credentials.h",
		"google/cloud/options.h",
		"google/cloud/version.h",
	})
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
std::shared_ptr<$stub_class_name$> CreateDefault$stub_class_name$(
    std::shared_ptr<internal::GrpcAuthenticationStrategy> auth,
    Options const& options);
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateStubFactoryCc(svc *api.Service, serviceVars map[string]string, methods []*api.Method, _ *config.Library) (string, string) {
	ccPath := serviceVars["stub_factory_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{
		vars["stub_factory_header_path"],
		vars["auth_header_path"],
		vars["logging_header_path"],
		vars["metadata_header_path"],
		vars["stub_header_path"],
		vars["tracing_stub_header_path"],
		"google/cloud/common_options.h",
		"google/cloud/grpc_options.h",
		"google/cloud/internal/algorithm.h",
		"google/cloud/internal/opentelemetry.h",
		"google/cloud/log.h",
		"google/cloud/options.h",
	})

	var pbIncludes []string
	if vars["proto_grpc_header_path"] != "" {
		pbIncludes = append(pbIncludes, vars["proto_grpc_header_path"])
	}
	allMixins := getMixinStubs(svc, methods)
	for _, mixin := range allMixins {
		if mixin.header != "" {
			pbIncludes = append(pbIncludes, mixin.header)
		}
	}
	p.ProtobufIncludes(pbIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	hasLro := hasLongrunningMethod(methods)
	var filteredMixins []mixinStubInfo
	for _, mixin := range allMixins {
		if hasLro && mixin.stubName == "operations_stub" {
			continue
		}
		filteredMixins = append(filteredMixins, mixin)
	}

	var mixinInits strings.Builder
	var mixinMoves strings.Builder
	for _, mixin := range filteredMixins {
		fmt.Fprintf(&mixinInits, "\n  auto service_%s = %s::NewStub(channel);", mixin.stubName, mixin.stubFQN)
		fmt.Fprintf(&mixinMoves, ", std::move(service_%s)", mixin.stubName)
	}

	p.Print(`
std::shared_ptr<$stub_class_name$>
CreateDefault$stub_class_name$(
    std::shared_ptr<internal::GrpcAuthenticationStrategy> auth,
    Options const& options) {
  auto channel = auth->CreateChannel(
    options.get<EndpointOption>(), internal::MakeChannelArguments(options));
  auto service_grpc_stub = $grpc_stub_fqn$::NewStub(channel);`)

	p.Print(mixinInits.String())

	if !hasLro {
		p.Print(fmt.Sprintf(`
  std::shared_ptr<$stub_class_name$> stub =
    std::make_shared<Default$stub_class_name$>(std::move(service_grpc_stub)%s);
`, mixinMoves.String()))
	} else {
		p.Print(fmt.Sprintf(`
  std::shared_ptr<$stub_class_name$> stub =
    std::make_shared<Default$stub_class_name$>(
      std::move(service_grpc_stub)%s,
      google::longrunning::Operations::NewStub(channel));
`, mixinMoves.String()))
	}

	p.Print(`
  if (auth->RequiresConfigureContext()) {
    stub = std::make_shared<$auth_class_name$>(
        std::move(auth), std::move(stub));
  }
  stub = std::make_shared<$metadata_class_name$>(
      std::move(stub), std::multimap<std::string, std::string>{});
  if (internal::Contains(
      options.get<LoggingComponentsOption>(), "rpc")) {
    GCP_LOG(INFO) << "Enabled logging for gRPC calls";
    stub = std::make_shared<$logging_class_name$>(
        std::move(stub),
        options.get<GrpcTracingOptionsOption>(),
        options.get<LoggingComponentsOption>());
  }
  if (internal::TracingEnabled(options)) {
    stub = Make$tracing_stub_class_name$(std::move(stub));
  }
  return stub;
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
