// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateConnectionHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["connection_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	var localIncludes []string
	localIncludes = append(localIncludes,
		vars["idempotency_policy_header_path"],
		vars["retry_traits_header_path"],
		"google/cloud/backoff_policy.h",
		"google/cloud/internal/retry_policy_impl.h",
		"google/cloud/options.h",
		"google/cloud/status_or.h",
		"google/cloud/version.h",
	)
	if hasLongrunningMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/no_await_tag.h", "google/cloud/polling_policy.h")
	}
	if hasLongrunningMethod(methods) || hasAsyncMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/future.h")
	}
	if hasStreamingReadMethod(methods) || hasPaginatedMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/stream_range.h")
	}
	if hasBidiStreamingMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_read_write_stream_impl.h")
	}
	p.HeaderLocalIncludes(localIncludes)

	var protoIncludes []string
	if addPaths, ok := vars["additional_pb_header_paths"]; ok && addPaths != "" {
		for add := range strings.SplitSeq(addPaths, ",") {
			if add != "" {
				protoIncludes = append(protoIncludes, add)
			}
		}
	}
	protoIncludes = append(protoIncludes, vars["proto_header_path"])
	if hasLongrunningMethod(methods) {
		protoIncludes = append(protoIncludes, "google/longrunning/operations.grpc.pb.h")
	}
	p.ProtobufIncludes(protoIncludes)

	hasGrpc := lib == nil || lib.Cpp == nil || lib.Cpp.HasGrpcTransport()
	locationStyle := ""
	if lib != nil && lib.Cpp != nil {
		locationStyle = lib.Cpp.EndpointLocationStyle
	}
	isLocationDependent := locationStyle == "LOCATION_DEPENDENT" ||
		locationStyle == "LOCATION_DEPENDENT_COMPAT" ||
		locationStyle == "LOCATION_OPTIONALLY_DEPENDENT"

	sysIncludes := []string{"memory"}
	if hasGrpc && isLocationDependent {
		sysIncludes = append(sysIncludes, "string")
	}
	p.SystemIncludes(sysIncludes)

	p.HeaderOpenNamespaces(vars["product_namespace"])

	p.Print(`
/// The retry policy for ` + "`$connection_class_name$`" + `.
class $retry_policy_name$ : public ::google::cloud::RetryPolicy {
 public:
  /// Creates a new instance of the policy, reset to the initial state.
  virtual std::unique_ptr<$retry_policy_name$> clone() const = 0;
};

/**
 * A retry policy for ` + "`$connection_class_name$`" + ` based on counting errors.
 *
 * This policy stops retrying if:
 * - An RPC returns a non-transient error.
 * - More than a prescribed number of transient failures is detected.
 *$transient_errors_comment$
 */
class $limited_error_count_retry_policy_name$ : public $retry_policy_name$ {
 public:
  /**
   * Create an instance that tolerates up to @p maximum_failures transient
   * errors.
   *
   * @note Disable the retry loop by providing an instance of this policy with
   *     @p maximum_failures == 0.
   */
  explicit $limited_error_count_retry_policy_name$(int maximum_failures)
    : impl_(maximum_failures) {}

  $limited_error_count_retry_policy_name$(
      $limited_error_count_retry_policy_name$&& rhs) noexcept
    : $limited_error_count_retry_policy_name$(rhs.maximum_failures()) {}
  $limited_error_count_retry_policy_name$(
      $limited_error_count_retry_policy_name$ const& rhs) noexcept
    : $limited_error_count_retry_policy_name$(rhs.maximum_failures()) {}

  int maximum_failures() const { return impl_.maximum_failures(); }

  bool OnFailure(Status const& status) override {
    return impl_.OnFailure(status);
  }
  bool IsExhausted() const override { return impl_.IsExhausted(); }
  bool IsPermanentFailure(Status const& status) const override {
    return impl_.IsPermanentFailure(status);
  }
  std::unique_ptr<$retry_policy_name$> clone() const override {
    return std::make_unique<$limited_error_count_retry_policy_name$>(
        maximum_failures());
  }

  // This is provided only for backwards compatibility.
  using BaseType = $retry_policy_name$;

 private:
  google::cloud::internal::LimitedErrorCountRetryPolicy<$product_internal_namespace$::$retry_traits_name$> impl_;
};

/**
 * A retry policy for ` + "`$connection_class_name$`" + ` based on elapsed time.
 *
 * This policy stops retrying if:
 * - An RPC returns a non-transient error.
 * - The elapsed time in the retry loop exceeds a prescribed duration.
 *$transient_errors_comment$
 */
class $limited_time_retry_policy_name$ : public $retry_policy_name$ {
 public:
  /**
   * Constructor given a ` + "`std::chrono::duration<>`" + ` object.
   *
   * @tparam DurationRep a placeholder to match the ` + "`Rep`" + ` tparam for @p
   *     duration's type. The semantics of this template parameter are
   *     documented in ` + "`std::chrono::duration<>`" + `. In brief, the underlying
   *     arithmetic type used to store the number of ticks. For our purposes it
   *     is simply a formal parameter.
   * @tparam DurationPeriod a placeholder to match the ` + "`Period`" + ` tparam for @p
   *     duration's type. The semantics of this template parameter are
   *     documented in ` + "`std::chrono::duration<>`" + `. In brief, the length of the
   *     tick in seconds, expressed as a ` + "`std::ratio<>`" + `. For our purposes it is
   *     simply a formal parameter.
   * @param maximum_duration the maximum time allowed before the policy expires.
   *     While the application can express this time in any units they desire,
   *     the class truncates to milliseconds.
   *
   * @see https://en.cppreference.com/w/cpp/chrono/duration for more information
   *     about ` + "`std::chrono::duration`" + `.
   */
  template <typename DurationRep, typename DurationPeriod>
  explicit $limited_time_retry_policy_name$(
      std::chrono::duration<DurationRep, DurationPeriod> maximum_duration)
    : impl_(maximum_duration) {}

  $limited_time_retry_policy_name$($limited_time_retry_policy_name$&& rhs) noexcept
    : $limited_time_retry_policy_name$(rhs.maximum_duration()) {}
  $limited_time_retry_policy_name$($limited_time_retry_policy_name$ const& rhs) noexcept
    : $limited_time_retry_policy_name$(rhs.maximum_duration()) {}

  std::chrono::milliseconds maximum_duration() const {
    return impl_.maximum_duration();
  }

  bool OnFailure(Status const& status) override {
    return impl_.OnFailure(status);
  }
  bool IsExhausted() const override { return impl_.IsExhausted(); }
  bool IsPermanentFailure(Status const& status) const override {
    return impl_.IsPermanentFailure(status);
  }
  std::unique_ptr<$retry_policy_name$> clone() const override {
    return std::make_unique<$limited_time_retry_policy_name$>(
        maximum_duration());
  }

  // This is provided only for backwards compatibility.
  using BaseType = $retry_policy_name$;

 private:
  google::cloud::internal::LimitedTimeRetryPolicy<$product_internal_namespace$::$retry_traits_name$> impl_;
};

/**
 * The ` + "`$connection_class_name$`" + ` object for ` + "`$client_class_name$`" + `.
 *
 * This interface defines virtual methods for each of the user-facing overload
 * sets in ` + "`$client_class_name$`" + `. This allows users to inject custom behavior
 * (e.g., with a Google Mock object) when writing tests that use objects of type
 * ` + "`$client_class_name$`" + `.
 *
 * To create a concrete instance, see ` + "`Make$connection_class_name$()`" + `.
 *
 * For mocking, see ` + "`$product_mocks_namespace$::$mock_connection_class_name$`" + `.
 */
class $connection_class_name$ {
 public:
  virtual ~$connection_class_name$() = 0;

  virtual Options options() { return Options{}; }
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
  virtual std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
      $request_type$,
      $response_type$>>
  Async$method_name$();
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  virtual StreamRange<$response_type$>
  $method_name$($request_type$ const& request);
`)
			continue
		}
		if isStreamingWrite(m) {
			continue
		}
		if isPaginated(m) {
			p.PrintWith(mVars, `
  virtual StreamRange<$range_output_type$>
  $method_name$($request_type$ request);
`)
			continue
		}
		if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
  virtual future<Status>
  $method_name$($request_type$ const& request);

  virtual Status
  $method_name$(NoAwaitTag, $request_type$ const& request);

  virtual future<Status>
  $method_name$( $longrunning_operation_type$ const& operation);
`)
			} else {
				p.PrintWith(mVars, `
  virtual future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($request_type$ const& request);

  virtual StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag, $request_type$ const& request);

  virtual future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$( $longrunning_operation_type$ const& operation);
`)
			}
			continue
		}
		p.PrintWith(mVars, `
  virtual $return_type$
  $method_name$($request_type$ const& request);
`)
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  virtual future<$return_type$>
  Async$method_name$($request_type$ const& request);
`)
	}

	p.Print(`};
`)

	if hasGrpc {
		locationDoc := ""
		if isLocationDependent {
			locationDoc = "\n * @param location Sets the prefix for the default `EndpointOption` value."
		}

		p.Print(`
/**
 * A factory function to construct an object of type ` + "`$connection_class_name$`" + `.
 *
 * The returned connection object should not be used directly; instead it
 * should be passed as an argument to the constructor of $client_class_name$.
 *
 * The optional @p options argument may be used to configure aspects of the
 * returned ` + "`$connection_class_name$`" + `. Expected options are any of the types in
 * the following option lists:
 *
 * - ` + "`google::cloud::CommonOptionList`" + `
 * - ` + "`google::cloud::GrpcOptionList`" + `
 * - ` + "`google::cloud::UnifiedCredentialsOptionList`" + `
 * - ` + "`google::cloud::$product_namespace$::$service_name$PolicyOptionList`" + `
 *
 * @note Unexpected options will be ignored. To log unexpected options instead,
 *     set ` + "`GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes`" + ` in the environment.
 *` + locationDoc + `
 * @param options (optional) Configure the ` + "`$connection_class_name$`" + ` created by
 * this function.
 */
std::shared_ptr<$connection_class_name$> Make$connection_class_name$(
`)
		if isLocationDependent {
			p.Print(`    std::string const& location, Options options = {});
`)
			switch locationStyle {
			case "LOCATION_DEPENDENT_COMPAT":
				p.Print(`
/**
 * A backwards-compatible version of the previous factory function.  Unless
 * the service also offers a global endpoint, the default value of the
 * ` + "`EndpointOption`" + ` may be useless, in which case it must be overridden.
 *
 * @deprecated Please use the ` + "`location`" + ` overload instead.
 */
std::shared_ptr<$connection_class_name$> Make$connection_class_name$(
    Options options = {});
`)
			case "LOCATION_OPTIONALLY_DEPENDENT":
				p.Print(`
/**
 * A factory function to construct an object of type ` + "`$connection_class_name$`" + `.
 *
 * This overload of ` + "`Make$connection_class_name$`" + ` does not require a location
 * argument, creating a connection to the global service endpoint.
 */
std::shared_ptr<$connection_class_name$> Make$connection_class_name$(
    Options options = {});
`)
			}
		} else {
			p.Print(`    Options options = {});
`)
		}
	}

	p.HeaderCloseNamespaces(vars["product_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateConnectionCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["connection_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	hasGrpc := lib == nil || lib.Cpp == nil || lib.Cpp.HasGrpcTransport()

	var localIncludes []string
	localIncludes = append(localIncludes,
		vars["connection_header_path"],
		vars["options_header_path"],
	)
	if hasGrpc {
		localIncludes = append(localIncludes, vars["connection_impl_header_path"])
	}
	localIncludes = append(localIncludes, vars["option_defaults_header_path"])
	if hasGrpc {
		localIncludes = append(localIncludes, vars["stub_factory_header_path"])
	}
	localIncludes = append(localIncludes,
		vars["tracing_connection_header_path"],
		"google/cloud/background_threads.h",
		"google/cloud/common_options.h",
		"google/cloud/credentials.h",
		"google/cloud/grpc_options.h",
		"google/cloud/internal/unified_grpc_credentials.h",
	)
	if hasPaginatedMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/pagination_range.h")
	}
	p.CcLocalIncludes(localIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_namespace"])

	p.Print(`
$connection_class_name$::~$connection_class_name$() = default;
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$connection_class_name$::Async$method_name$() {
  return std::make_unique<
      ::google::cloud::internal::AsyncStreamingReadWriteRpcError<
          $request_type$,
          $response_type$>>(
      Status(StatusCode::kUnimplemented, "not implemented"));
}
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
StreamRange<$response_type$> $connection_class_name$::$method_name$(
    $request_type$ const&) {
  return google::cloud::internal::MakeStreamRange<
      $response_type$>(
      []() -> absl::variant<Status,
      $response_type$>{
        return Status(StatusCode::kUnimplemented, "not implemented");}
      );
}
`)
			continue
		}
		if isStreamingWrite(m) {
			continue
		}
		if isPaginated(m) {
			p.PrintWith(mVars, `
StreamRange<$range_output_type$> $connection_class_name$::$method_name$(
    $request_type$) {  // NOLINT(performance-unnecessary-value-param)
  return google::cloud::internal::MakeUnimplementedPaginationRange<
      StreamRange<$range_output_type$>>();
}
`)
			continue
		}
		if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
future<Status>
$connection_class_name$::$method_name$(
    $request_type$ const&) {
  return google::cloud::make_ready_future(
    Status(StatusCode::kUnimplemented, "not implemented"));
}

Status
$connection_class_name$::$method_name$(
    NoAwaitTag,
    $request_type$ const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

future<Status>
$connection_class_name$::$method_name$(
    $longrunning_operation_type$ const&) {
  return google::cloud::make_ready_future(
    Status(StatusCode::kUnimplemented, "not implemented"));
}
`)
			} else {
				p.PrintWith(mVars, `
future<StatusOr<$longrunning_deduced_response_type$>>
$connection_class_name$::$method_name$(
    $request_type$ const&) {
  return google::cloud::make_ready_future<
    StatusOr<$longrunning_deduced_response_type$>>(
    Status(StatusCode::kUnimplemented, "not implemented"));
}

StatusOr<$longrunning_operation_type$>
$connection_class_name$::$method_name$(
    NoAwaitTag,
    $request_type$ const&) {
  return StatusOr<$longrunning_operation_type$>(
    Status(StatusCode::kUnimplemented, "not implemented"));
}

future<StatusOr<$longrunning_deduced_response_type$>>
$connection_class_name$::$method_name$(
    $longrunning_operation_type$ const&) {
  return google::cloud::make_ready_future<
    StatusOr<$longrunning_deduced_response_type$>>(
    Status(StatusCode::kUnimplemented, "not implemented"));
}
`)
			}
			continue
		}
		p.PrintWith(mVars, `
$return_type$
$connection_class_name$::$method_name$(
    $request_type$ const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}
`)
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isResponseTypeEmpty(m) {
			p.PrintWith(mVars, `
future<Status>
$connection_class_name$::Async$method_name$(
    $request_type$ const&) {
  return google::cloud::make_ready_future(
      Status(StatusCode::kUnimplemented, "not implemented"));
}
`)
		} else {
			p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
$connection_class_name$::Async$method_name$(
    $request_type$ const&) {
  return google::cloud::make_ready_future<
    StatusOr<$response_type$>>(
    Status(StatusCode::kUnimplemented, "not implemented"));
}
`)
		}
	}

	if hasGrpc {
		locationStyle := ""
		if lib != nil && lib.Cpp != nil {
			locationStyle = lib.Cpp.EndpointLocationStyle
		}
		isLocationDependent := locationStyle == "LOCATION_DEPENDENT" ||
			locationStyle == "LOCATION_DEPENDENT_COMPAT" ||
			locationStyle == "LOCATION_OPTIONALLY_DEPENDENT"

		if isLocationDependent {
			p.Print(`
std::shared_ptr<$connection_class_name$> Make$connection_class_name$(
    std::string const& location, Options options) {
  internal::CheckExpectedOptions<CommonOptionList, GrpcOptionList,
      UnifiedCredentialsOptionList,
      $service_name$PolicyOptionList>(options, __func__);
  options = $product_internal_namespace$::$service_name$DefaultOptions(
      location, std::move(options));
  auto background = internal::MakeBackgroundThreadsFactory(options)();
  auto auth = internal::CreateAuthenticationStrategy(background->cq(), options);
  auto stub = $product_internal_namespace$::CreateDefault$stub_class_name$(
    std::move(auth), options);
  return $product_internal_namespace$::Make$tracing_connection_class_name$(
      std::make_shared<$product_internal_namespace$::$connection_class_name$Impl>(
      std::move(background), std::move(stub), std::move(options)));
}
`)
			if locationStyle == "LOCATION_DEPENDENT_COMPAT" || locationStyle == "LOCATION_OPTIONALLY_DEPENDENT" {
				p.Print(`
std::shared_ptr<$connection_class_name$> Make$connection_class_name$(
    Options options) {
  return Make$connection_class_name$(std::string{}, std::move(options));
}
`)
			}
		} else {
			p.Print(`
std::shared_ptr<$connection_class_name$> Make$connection_class_name$(
    Options options) {
  internal::CheckExpectedOptions<CommonOptionList, GrpcOptionList,
      UnifiedCredentialsOptionList,
      $service_name$PolicyOptionList>(options, __func__);
  options = $product_internal_namespace$::$service_name$DefaultOptions(
      std::move(options));
  auto background = internal::MakeBackgroundThreadsFactory(options)();
  auto auth = internal::CreateAuthenticationStrategy(background->cq(), options);
  auto stub = $product_internal_namespace$::CreateDefault$stub_class_name$(
    std::move(auth), options);
  return $product_internal_namespace$::Make$tracing_connection_class_name$(
      std::make_shared<$product_internal_namespace$::$connection_class_name$Impl>(
      std::move(background), std::move(stub), std::move(options)));
}
`)
		}
	}

	p.HeaderCloseNamespaces(vars["product_namespace"])

	return filepath.Clean(ccPath), p.String()
}
