// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateRestStubHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["stub_rest_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		"google/cloud/completion_queue.h",
		"google/cloud/internal/rest_client.h",
		"google/cloud/internal/rest_context.h",
		"google/cloud/status_or.h",
		"google/cloud/version.h",
	})

	var additionalProtoIncludes []string
	if addPaths, ok := vars["additional_pb_header_paths"]; ok && addPaths != "" {
		for add := range strings.SplitSeq(addPaths, ",") {
			if add != "" {
				additionalProtoIncludes = append(additionalProtoIncludes, add)
			}
		}
	}
	p.ProtobufIncludes(additionalProtoIncludes)

	var mixinHeaders []string
	seenMixin := make(map[string]bool)
	for _, m := range methods {
		if m.SourceService != nil && m.SourceService.ID != svc.ID {
			h := ""
			if loc, ok := model.DefinitionLocation(m.SourceService.ID[1:]); ok {
				h = strings.TrimSuffix(loc.Filename, ".proto") + ".pb.h"
			} else if m.SourceService.ID == ".google.cloud.location.Locations" {
				h = "google/cloud/location/locations.pb.h"
			} else if m.SourceService.ID == ".google.iam.v1.IAMPolicy" {
				h = "google/iam/v1/iam_policy.pb.h"
			} else if m.SourceService.ID == ".google.longrunning.Operations" {
				h = "google/longrunning/operations.pb.h"
			}
			if h != "" && !seenMixin[h] {
				seenMixin[h] = true
				mixinHeaders = append(mixinHeaders, h)
			}
		}
	}
	p.ProtobufIncludes(mixinHeaders)

	var protoIncludes []string
	protoIncludes = append(protoIncludes, vars["proto_header_path"])
	if hasLongrunningMethod(methods) && !seenMixin["google/longrunning/operations.pb.h"] {
		protoIncludes = append(protoIncludes, "google/longrunning/operations.pb.h")
	}
	p.ProtobufIncludes(protoIncludes)
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $stub_rest_class_name$ {
 public:
  virtual ~$stub_rest_class_name$() = default;
`)

	restMethods := getRestMethods(methods)
	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			p.PrintWith(mVars, `
  virtual future<StatusOr<$response_type$>> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) = 0;

  virtual StatusOr<$response_type$> $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) = 0;
`)
		} else {
			p.PrintWith(mVars, `
  virtual $return_type$ $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) = 0;
`)
		}
	}

	restAsyncMethods := getRestAsyncMethods(asyncMethods)
	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  virtual future<$return_type$> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) = 0;
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
  virtual future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::GetOperationRequest const& request) = 0;

  virtual future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::CancelOperationRequest const& request) = 0;
`)
	}

	p.Print(`};

class Default$stub_rest_class_name$ : public $stub_rest_class_name$ {
 public:
  ~Default$stub_rest_class_name$() override = default;

  explicit Default$stub_rest_class_name$(Options options);
`)

	if hasLongrunningMethod(methods) {
		p.Print(`  Default$stub_rest_class_name$(
      std::shared_ptr<rest_internal::RestClient> service,
      std::shared_ptr<rest_internal::RestClient> operations,
      Options options);
`)
	} else {
		p.Print(`  Default$stub_rest_class_name$(
      std::shared_ptr<rest_internal::RestClient> service,
      Options options);
`)
	}

	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			p.PrintWith(mVars, `
  future<StatusOr<$response_type$>> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;

  StatusOr<$response_type$> $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) override;
`)
		} else {
			p.PrintWith(mVars, `
  $return_type$ $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) override;
`)
		}
	}

	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  future<$return_type$> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
  future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::GetOperationRequest const& request) override;

  future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::CancelOperationRequest const& request) override;
`)
	}

	p.Print(`
 private:
  std::shared_ptr<rest_internal::RestClient> service_;
`)

	if hasLongrunningMethod(methods) {
		p.Print(`  std::shared_ptr<rest_internal::RestClient> operations_;
`)
	}

	p.Print(`  Options options_;
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateRestStubCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["stub_rest_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{
		vars["stub_rest_header_path"],
		"google/cloud/common_options.h",
		"google/cloud/internal/absl_str_cat_quiet.h",
		"google/cloud/internal/rest_stub_helpers.h",
		"google/cloud/status_or.h",
	})

	var protoIncludes []string
	protoIncludes = append(protoIncludes, vars["proto_header_path"])
	if hasLongrunningMethod(methods) {
		protoIncludes = append(protoIncludes, "google/longrunning/operations.pb.h")
	}
	p.ProtobufIncludes(protoIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	if hasLongrunningMethod(methods) {
		p.Print(`
Default$stub_rest_class_name$::Default$stub_rest_class_name$(Options options)
    : service_(rest_internal::MakePooledRestClient(
          options.get<EndpointOption>(), options)),
      operations_(rest_internal::MakePooledRestClient(
          options.get<rest_internal::LongrunningEndpointOption>(), options)),
      options_(std::move(options)) {}

Default$stub_rest_class_name$::Default$stub_rest_class_name$(
    std::shared_ptr<rest_internal::RestClient> service,
    std::shared_ptr<rest_internal::RestClient> operations,
    Options options)
    : service_(std::move(service)),
      operations_(std::move(operations)),
      options_(std::move(options)) {}
`)
	} else {
		p.Print(`
Default$stub_rest_class_name$::Default$stub_rest_class_name$(Options options)
    : service_(rest_internal::MakePooledRestClient(
          options.get<EndpointOption>(), options)),
      options_(std::move(options)) {}

Default$stub_rest_class_name$::Default$stub_rest_class_name$(
    std::shared_ptr<rest_internal::RestClient> service,
    Options options)
    : service_(std::move(service)),
      options_(std::move(options)) {}
`)
	}

	restMethods := getRestMethods(methods)
	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
Default$stub_rest_class_name$::Async$method_name$(
      CompletionQueue& cq,
      std::unique_ptr<rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  promise<StatusOr<$response_type$>> p;
  future<StatusOr<$response_type$>> f = p.get_future();
  std::thread t{[](
          auto p, auto service, auto request, auto rest_context, auto options) {
      std::vector<std::pair<std::string, std::string>> query_params;$method_http_query_parameters$
      p.set_value(rest_internal::$method_http_verb$<$response_type$>(
          *service, *rest_context, $request_resource$,
          $preserve_proto_field_names_in_json$,
          $method_rest_path_async$, std::move(query_params)));
    },
    std::move(p), service_, request, std::move(rest_context),
    std::move(options)};
  return f.then([t = std::move(t), cq](auto f) mutable {
    cq.RunAsync([t = std::move(t)]() mutable {
      t.join();
    });
    return f.get();
  });
}

StatusOr<$response_type$>
Default$stub_rest_class_name$::$method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options,
      $request_type$ const& request) {
  std::vector<std::pair<std::string, std::string>> query_params;$method_http_query_parameters$
  return rest_internal::$method_http_verb$<$response_type$>(
      *service_, rest_context, $request_resource$, $preserve_proto_field_names_in_json$,
      $method_rest_path$, std::move(query_params));
}
`)
		} else {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
Status Default$stub_rest_class_name$::$method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options,
      $request_type$ const& request) {
  std::vector<std::pair<std::string, std::string>> query_params;$method_http_query_parameters$
  return rest_internal::$method_http_verb$<google::cloud::rest_internal::EmptyResponseType>(
      *service_, rest_context, $request_resource$, $preserve_proto_field_names_in_json$,
      $method_rest_path$, std::move(query_params));
}
`)
			} else {
				p.PrintWith(mVars, `
StatusOr<$response_type$>
Default$stub_rest_class_name$::$method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options,
      $request_type$ const& request) {
  std::vector<std::pair<std::string, std::string>> query_params;$method_http_query_parameters$
  return rest_internal::$method_http_verb$<$response_type$>(
      *service_, rest_context, $request_resource$, $preserve_proto_field_names_in_json$,
      $method_rest_path$, std::move(query_params));
}
`)
			}
		}
	}

	restAsyncMethods := getRestAsyncMethods(asyncMethods)
	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isResponseTypeEmpty(m) {
			p.PrintWith(mVars, `
future<Status>
Default$stub_rest_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  promise<StatusOr<google::protobuf::Empty>> p;
  future<StatusOr<google::protobuf::Empty>> f = p.get_future();
  std::thread t{[](
          auto p, auto service, auto request, auto rest_context, auto options) {
      std::vector<std::pair<std::string, std::string>> query_params;$method_http_query_parameters$
      p.set_value(rest_internal::$method_http_verb$<google::protobuf::Empty>(
          *service, *rest_context, $request_resource$, $preserve_proto_field_names_in_json$,
          $method_rest_path_async$, std::move(query_params)));
    },
    std::move(p), service_, request, std::move(rest_context),
    std::move(options)};
  return f.then([t = std::move(t), cq](auto f) mutable {
    cq.RunAsync([t = std::move(t)]() mutable {
      t.join();
    });
    return f.get().status();
  });
}
`)
		} else {
			p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
Default$stub_rest_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  promise<StatusOr<$response_type$>> p;
  future<StatusOr<$response_type$>> f = p.get_future();
  std::thread t{[](
          auto p, auto service, auto request, auto rest_context, auto options) {
      std::vector<std::pair<std::string, std::string>> query_params;$method_http_query_parameters$
      p.set_value(rest_internal::$method_http_verb$<$response_type$>(
          *service, *rest_context, $request_resource$, $preserve_proto_field_names_in_json$,
          $method_rest_path_async$, std::move(query_params)));
    },
    std::move(p), service_, request, std::move(rest_context),
    std::move(options)};
  return f.then([t = std::move(t), cq](auto f) mutable {
    cq.RunAsync([t = std::move(t)]() mutable {
      t.join();
    });
    return f.get();
  });
}
`)
		}
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
Default$stub_rest_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::GetOperationRequest const& request) {
  promise<StatusOr<google::longrunning::Operation>> p;
  future<StatusOr<google::longrunning::Operation>> f = p.get_future();
  std::thread t{[](auto p, auto operations, auto request, auto rest_context, auto options) {
      p.set_value(rest_internal::Get<google::longrunning::Operation>(
          *operations, *rest_context, request, $preserve_proto_field_names_in_json$,
          $longrunning_get_operation_path_rest$));
    },
    std::move(p), operations_, request, std::move(rest_context),
    std::move(options)};
  return f.then([t = std::move(t), cq](auto f) mutable {
    cq.RunAsync([t = std::move(t)]() mutable {
      t.join();
    });
    return f.get();
  });
}

future<Status>
Default$stub_rest_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::CancelOperationRequest const& request) {
  promise<StatusOr<google::protobuf::Empty>> p;
  future<StatusOr<google::protobuf::Empty>> f = p.get_future();
  std::thread t{[](auto p, auto operations, auto request, auto rest_context, auto options) {
      p.set_value(rest_internal::Post<google::protobuf::Empty>(
          *operations, *rest_context, request, $preserve_proto_field_names_in_json$,
          $longrunning_cancel_operation_path_rest$));
    },
    std::move(p), operations_, request, std::move(rest_context),
    std::move(options)};
  return f.then([t = std::move(t), cq](auto f) mutable {
    cq.RunAsync([t = std::move(t)]() mutable {
      t.join();
    });
    return f.get().status();
  });
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	return filepath.Clean(ccPath), p.String()
}
