// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateRestConnectionImplHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["connection_impl_rest_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	restMethods := getRestMethods(methods)
	restAsyncMethods := getRestAsyncMethods(asyncMethods)

	var localIncludes []string
	localIncludes = append(localIncludes,
		vars["connection_header_path"],
		vars["idempotency_policy_header_path"],
		vars["options_header_path"],
		vars["stub_rest_header_path"],
		vars["retry_traits_header_path"],
		"google/cloud/background_threads.h",
		"google/cloud/backoff_policy.h",
		"google/cloud/options.h",
		"google/cloud/status_or.h",
	)
	if hasPaginatedMethod(restMethods) {
		localIncludes = append(localIncludes, "google/cloud/stream_range.h")
	}
	localIncludes = append(localIncludes, "google/cloud/version.h")
	p.HeaderLocalIncludes(localIncludes)

	if hasLongrunningMethod(restMethods) {
		p.ProtobufIncludes([]string{"google/longrunning/operations.pb.h"})
	}
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $connection_impl_rest_class_name$
    : public $product_namespace$::$connection_class_name$ {
 public:
  ~$connection_impl_rest_class_name$() override = default;

  $connection_impl_rest_class_name$(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<$product_internal_namespace$::$stub_rest_class_name$> stub,
    Options options);

  Options options() override { return options_; }
`)

	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isPaginated(m) {
			p.PrintWith(mVars, `
  StreamRange<$range_output_type$>
  $method_name$($request_type$ request) override;
`)
		} else if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
  future<Status>
  $method_name$($request_type$ const& request) override;

  Status
  $method_name$(NoAwaitTag,
      $request_type$ const& request) override;

  future<Status>
  $method_name$(
      $longrunning_operation_type$ const& operation) override;
`)
			} else {
				p.PrintWith(mVars, `
  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($request_type$ const& request) override;

  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag,
      $request_type$ const& request) override;

  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$(
      $longrunning_operation_type$ const& operation) override;
`)
			}
		} else {
			p.PrintWith(mVars, `
  $return_type$
  $method_name$($request_type$ const& request) override;
`)
		}
	}

	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  future<$return_type$>
  Async$method_name$($request_type$ const& request) override;
`)
	}

	p.Print(`
 private:
  static std::unique_ptr<$product_namespace$::$retry_policy_name$>
  retry_policy(Options const& options) {
    return options.get<$product_namespace$::$retry_policy_name$Option>()->clone();
  }

  static std::unique_ptr<BackoffPolicy> backoff_policy(Options const& options) {
    return options.get<$product_namespace$::$service_name$BackoffPolicyOption>()->clone();
  }

  static std::unique_ptr<$product_namespace$::$idempotency_class_name$>
  idempotency_policy(Options const& options) {
    return options.get<$product_namespace$::$idempotency_class_name$Option>()->clone();
  }
`)

	if hasLongrunningMethod(restMethods) {
		p.Print(`
  static std::unique_ptr<PollingPolicy> polling_policy(Options const& options) {
    return options.get<$product_namespace$::$service_name$PollingPolicyOption>()->clone();
  }
`)
	}

	p.Print(`
  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<$product_internal_namespace$::$stub_rest_class_name$> stub_;
  Options options_;
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateRestConnectionImplCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["connection_impl_rest_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	restMethods := getRestMethods(methods)
	restAsyncMethods := getRestAsyncMethods(asyncMethods)

	var localIncludes []string
	localIncludes = append(localIncludes,
		vars["connection_impl_rest_header_path"],
		vars["stub_factory_rest_header_path"],
		"google/cloud/common_options.h",
		"google/cloud/credentials.h",
	)
	if hasLongrunningMethod(restMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_rest_long_running_operation.h")
	}
	if len(asyncMethods) > 0 {
		localIncludes = append(localIncludes, "google/cloud/internal/async_rest_retry_loop.h")
	}
	if hasLongrunningMethod(restMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/extract_long_running_result.h")
	}
	if hasPaginatedMethod(restMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/pagination_range.h")
	}
	localIncludes = append(localIncludes,
		"google/cloud/internal/rest_retry_loop.h",
		"google/cloud/rest_options.h",
	)
	p.CcLocalIncludes(localIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
$connection_impl_rest_class_name$::$connection_impl_rest_class_name$(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<$product_internal_namespace$::$stub_rest_class_name$> stub,
    Options options)
  : background_(std::move(background)), stub_(std::move(stub)),
    options_(internal::MergeOptions(
        std::move(options),
        $connection_class_name$::options())) {}
`)

	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isPaginated(m) {
			p.PrintWith(mVars, `
StreamRange<$range_output_type$>
$connection_impl_rest_class_name$::$method_name$($request_type$ request) {
  request.clear_page_token();
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto idempotency = idempotency_policy(*current)->$method_name$(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<$range_output_type$>>(
      current, std::move(request),
      [idempotency, function_name, stub = stub_,
       retry = std::shared_ptr<$product_namespace$::$retry_policy_name$>(retry_policy(*current)),
       backoff = std::shared_ptr<BackoffPolicy>(backoff_policy(*current))](
          Options const& options, $request_type$ const& r) {
        return google::cloud::rest_internal::RestRetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](rest_internal::RestContext& rest_context,
                   Options const& options,
                   $request_type$ const& request) {
              return stub->$method_name$(rest_context, options, request);
            },
            options, r, function_name);
      },
      []($response_type$ r) {
        std::vector<$range_output_type$> result(r.$range_output_field_name$().size());
        auto& messages = *r.mutable_$range_output_field_name$();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}
`)
		} else if isLongrunning(m) {
			extractor := "&google::cloud::internal::ExtractLongRunningResultResponse<" + mVars["longrunning_deduced_response_type"] + ">"
			if isLongrunningMetadataTypeUsedAsResponse(m) {
				extractor = "&google::cloud::internal::ExtractLongRunningResultMetadata<" + mVars["longrunning_deduced_response_type"] + ">"
			}

			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
future<Status>
$connection_impl_rest_class_name$::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return rest_internal::AsyncRestLongRunningOperation<google::protobuf::Empty>(
    background_->cq(), current, request,
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options, $request_type$ const& request) {
      return stub->Async$method_name$(
          cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::GetOperationRequest const& request) {
      return stub->AsyncGetOperation(
          cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::CancelOperationRequest const& request) {
      return stub->AsyncCancelOperation(
          cq, std::move(context), std::move(options), request);
    },
    &google::cloud::internal::ExtractLongRunningResultEmpty,
    retry_policy(*current), backoff_policy(*current),
    idempotency_policy(*current)->$method_name$(request),
    polling_policy(*current), __func__);

}

Status
$connection_impl_rest_class_name$::$method_name$(NoAwaitTag, $request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->$method_name$(request),
      [this](rest_internal::RestContext& rest_context,
             Options const& options, $request_type$ const& request) {
        return stub_->$method_name$(rest_context, options, request);
      },
      *current, request, __func__);
}

future<Status>
$connection_impl_rest_class_name$::$method_name$(
    google::longrunning::Operation const& operation) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  if (!operation.metadata().Is<typename $longrunning_metadata_type$>()) {
    return make_ready_future(
        internal::InvalidArgumentError("operation does not correspond to $method_name$",
                                       GCP_ERROR_INFO().WithMetadata("operation", operation.metadata().DebugString())));
  }
  return rest_internal::AsyncRestAwaitLongRunningOperation<google::protobuf::Empty>(
    background_->cq(), current, operation,
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::GetOperationRequest const& request) {
      return stub->AsyncGetOperation(
          cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::CancelOperationRequest const& request) {
      return stub->AsyncCancelOperation(
          cq, std::move(context), std::move(options), request);
    },
    &google::cloud::internal::ExtractLongRunningResultEmpty,
    polling_policy(*current), __func__);
}
`)
			} else {
				mVars["lro_extractor"] = extractor
				p.PrintWith(mVars, `
future<StatusOr<$longrunning_deduced_response_type$>>
$connection_impl_rest_class_name$::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return rest_internal::AsyncRestLongRunningOperation<$longrunning_deduced_response_type$>(
    background_->cq(), current, request,
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options, $request_type$ const& request) {
      return stub->Async$method_name$(
          cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::GetOperationRequest const& request) {
      return stub->AsyncGetOperation(
          cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::CancelOperationRequest const& request) {
      return stub->AsyncCancelOperation(
          cq, std::move(context), std::move(options), request);
    },
    $lro_extractor$,
    retry_policy(*current), backoff_policy(*current),
    idempotency_policy(*current)->$method_name$(request),
    polling_policy(*current), __func__);

}

StatusOr<$longrunning_operation_type$>
$connection_impl_rest_class_name$::$method_name$(NoAwaitTag, $request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->$method_name$(request),
      [this](rest_internal::RestContext& rest_context,
             Options const& options, $request_type$ const& request) {
        return stub_->$method_name$(rest_context, options, request);
      },
      *current, request, __func__);
}

future<StatusOr<$longrunning_deduced_response_type$>>
$connection_impl_rest_class_name$::$method_name$(
    google::longrunning::Operation const& operation) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  if (!operation.metadata().Is<typename $longrunning_metadata_type$>()) {
    return make_ready_future<StatusOr<$longrunning_deduced_response_type$>>(
        internal::InvalidArgumentError("operation does not correspond to $method_name$",
                                       GCP_ERROR_INFO().WithMetadata("operation", operation.metadata().DebugString())));
  }
  return rest_internal::AsyncRestAwaitLongRunningOperation<$longrunning_deduced_response_type$>(
    background_->cq(), current, operation,
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::GetOperationRequest const& request) {
      return stub->AsyncGetOperation(
          cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](CompletionQueue& cq,
                   std::unique_ptr<rest_internal::RestContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::CancelOperationRequest const& request) {
      return stub->AsyncCancelOperation(
          cq, std::move(context), std::move(options), request);
    },
    $lro_extractor$,
    polling_policy(*current), __func__);

}
`)
			}
		} else {
			p.PrintWith(mVars, `
$return_type$
$connection_impl_rest_class_name$::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::rest_internal::RestRetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->$method_name$(request),
      [this](rest_internal::RestContext& rest_context,
             Options const& options, $request_type$ const& request) {
        return stub_->$method_name$(rest_context, options, request);
      },
      *current, request, __func__);
}
`)
		}
	}

	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
future<$return_type$>
$connection_impl_rest_class_name$::Async$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto retry = retry_policy(*current);
  auto backoff = backoff_policy(*current);
  auto const idempotent = idempotency_policy(*current)->$method_name$(request);
  return rest_internal::AsyncRestRetryLoop(
      std::move(retry), std::move(backoff), idempotent, background_->cq(),
      [stub = stub_](CompletionQueue& cq,
                     std::unique_ptr<rest_internal::RestContext> context,
                     google::cloud::internal::ImmutableOptions options,
                     $request_type$ const& request) {
        return stub->Async$method_name$(
            cq, std::move(context), std::move(options), request);
      },
      std::move(current), request, __func__);
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	return filepath.Clean(ccPath), p.String()
}
