// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateTracingStubHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["tracing_stub_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_header_path"],
		"google/cloud/internal/trace_propagator.h",
		"google/cloud/options.h",
		"google/cloud/version.h",
	})
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

class $tracing_stub_class_name$ : public $stub_class_name$ {
 public:
  ~$tracing_stub_class_name$() override = default;

  explicit $tracing_stub_class_name$(std::shared_ptr<$stub_class_name$> child);
`)

	printDecoratorPublicMethods(p, svc, methods, asyncMethods, vars, lib, model)

	p.Print(`
 private:
  std::shared_ptr<$stub_class_name$> child_;
  std::shared_ptr<opentelemetry::context::propagation::TextMapPropagator> propagator_;
};

#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

/**
 * Applies the tracing decorator to the given stub.
 *
 * The stub is only decorated if the library has been compiled with
 * OpenTelemetry.
 */
std::shared_ptr<$stub_class_name$> Make$tracing_stub_class_name$(
    std::shared_ptr<$stub_class_name$> stub);
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateTracingStubCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["tracing_stub_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	localIncludes := []string{vars["tracing_stub_header_path"]}
	if hasAsynchronousStreamingReadMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_streaming_read_rpc_tracing.h")
	}
	if hasAsynchronousStreamingWriteMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_streaming_write_rpc_tracing.h")
	}
	if hasBidiStreamingMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_read_write_stream_tracing.h")
	}
	if hasStreamingReadMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/streaming_read_rpc_tracing.h")
	}
	if hasStreamingWriteMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/streaming_write_rpc_tracing.h")
	}
	localIncludes = append(localIncludes, "google/cloud/internal/grpc_opentelemetry.h")
	p.CcLocalIncludes(localIncludes)

	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

$tracing_stub_class_name$::$tracing_stub_class_name$(
    std::shared_ptr<$stub_class_name$> child)
    : child_(std::move(child)), propagator_(internal::MakePropagator()) {}
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		reqIdFragment := ""
		if len(m.AutoPopulated) > 0 {
			reqIdFragment = "\n  span->SetAttribute(\"gl-cpp.request_id\", request." + mVars["request_id_field_name"] + "());"
		}
		mVars["request_id_fragment"] = reqIdFragment

		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<internal::StreamingWriteRpc<$request_type$, $response_type$>>
$tracing_stub_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const& options) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");
  auto scope = opentelemetry::trace::Scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto stream = child_->$method_name$(context, options);
  return std::make_unique<
      internal::StreamingWriteRpcTracing<$request_type$, $response_type$>>(
      std::move(context), std::move(stream), std::move(span));
}
`)
			continue
		}
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$tracing_stub_class_name$::Async$method_name$(
    CompletionQueue const& cq, std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto stream = child_->Async$method_name$(cq, context, std::move(options));
  return std::make_unique<internal::AsyncStreamingReadWriteRpcTracing<
      $request_type$,
      $response_type$>>(
      std::move(context), std::move(stream), std::move(span));
}
`)
			continue
		}
		if isLongrunning(m) {
			p.PrintWith(mVars, `
future<StatusOr<google::longrunning::Operation>>
$tracing_stub_class_name$::Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");$request_id_fragment$
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto f = child_->Async$method_name$(cq, context, std::move(options), request);
  return internal::EndSpan(std::move(context), std::move(span), std::move(f));
}

StatusOr<google::longrunning::Operation>
$tracing_stub_class_name$::$method_name$(
      grpc::ClientContext& context,
      Options options,
      $request_type$ const& request) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");$request_id_fragment$
  auto scope = opentelemetry::trace::Scope(span);
  internal::InjectTraceContext(context, *propagator_);
  return internal::EndSpan(context, *span,
                           child_->$method_name$(context, options, request));
}
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::StreamingReadRpc<$response_type$>>
$tracing_stub_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const& options,
    $request_type$ const& request) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");
  auto scope = opentelemetry::trace::Scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto stream = child_->$method_name$(context, options, request);
  return std::make_unique<internal::StreamingReadRpcTracing<$response_type$>>(
      std::move(context), std::move(stream), std::move(span));
}
`)
			continue
		}
		p.PrintWith(mVars, `
$return_type$ $tracing_stub_class_name$::$method_name$(
    grpc::ClientContext& context,
    Options const& options,
    $request_type$ const& request) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");$request_id_fragment$
  auto scope = opentelemetry::trace::Scope(span);
  internal::InjectTraceContext(context, *propagator_);
  return internal::EndSpan(context, *span,
                           child_->$method_name$(context, options, request));
}
`)
	}

	for _, m := range asyncMethods {
		if isBidiStreaming(m) || isLongrunning(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		reqIdFragment := ""
		if len(m.AutoPopulated) > 0 {
			reqIdFragment = "\n  span->SetAttribute(\"gl-cpp.request_id\", request." + mVars["request_id_field_name"] + "());"
		}
		mVars["request_id_fragment"] = reqIdFragment

		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<internal::AsyncStreamingReadRpc<$response_type$>>
$tracing_stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto stream = child_->Async$method_name$(
      cq, context, std::move(options), request);
  return std::make_unique<
      internal::AsyncStreamingReadRpcTracing<$response_type$>>(
      std::move(context), std::move(stream), std::move(span));
}
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<
    internal::AsyncStreamingWriteRpc<$request_type$, $response_type$>>
$tracing_stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto stream = child_->Async$method_name$(cq, context, std::move(options));
  return std::make_unique<
      internal::AsyncStreamingWriteRpcTracing<$request_type$, $response_type$>>(
      std::move(context), std::move(stream), std::move(span));
}
`)
			continue
		}
		p.PrintWith(mVars, `
future<$return_type$>
$tracing_stub_class_name$::Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  auto span = internal::MakeSpanGrpc("$grpc_service$", "$method_name$");$request_id_fragment$
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto f = child_->Async$method_name$(cq, context, std::move(options), request);
  return internal::EndSpan(std::move(context), std::move(span), std::move(f));
}
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
$tracing_stub_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::GetOperationRequest const& request) {
  auto span =
      internal::MakeSpanGrpc("google.longrunning.Operations", "GetOperation");
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto f = child_->AsyncGetOperation(
      cq, context, std::move(options), request);
  return internal::EndSpan(std::move(context), std::move(span), std::move(f));
}

future<Status> $tracing_stub_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::CancelOperationRequest const& request) {
  auto span = internal::MakeSpanGrpc("google.longrunning.Operations",
                                     "CancelOperation");
  internal::OTelScope scope(span);
  internal::InjectTraceContext(*context, *propagator_);
  auto f = child_->AsyncCancelOperation(
      cq, context, std::move(options), request);
  return internal::EndSpan(std::move(context), std::move(span), std::move(f));
}
`)
	}

	p.Print(`
#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

std::shared_ptr<$stub_class_name$> Make$tracing_stub_class_name$(
    std::shared_ptr<$stub_class_name$> stub) {
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  return std::make_shared<$tracing_stub_class_name$>(std::move(stub));
#else
  return stub;
#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
