// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateRestLoggingDecoratorHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["logging_rest_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_rest_header_path"],
		"google/cloud/future.h",
		"google/cloud/internal/rest_context.h",
		"google/cloud/tracing_options.h",
		"google/cloud/version.h",
	})

	var protoIncludes []string
	protoIncludes = append(protoIncludes, vars["proto_header_path"])
	if hasLongrunningMethod(methods) {
		protoIncludes = append(protoIncludes, "google/longrunning/operations.pb.h")
	}
	p.ProtobufIncludes(protoIncludes)
	p.SystemIncludes([]string{"memory", "set", "string"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $logging_rest_class_name$ : public $stub_rest_class_name$ {
 public:
  ~$logging_rest_class_name$() override = default;
  $logging_rest_class_name$(std::shared_ptr<$stub_rest_class_name$> child,
                       TracingOptions tracing_options,
                       std::set<std::string> components);
`)

	restMethods := getRestMethods(methods)
	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			p.PrintWith(mVars, `
  future<StatusOr<$response_type$>> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;

  StatusOr<$response_type$> $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) override;
`)
		} else {
			p.PrintWith(mVars, `
  $return_type$ $method_name$(
      google::cloud::rest_internal::RestContext& rest_context,
      Options const& options, $request_type$ const& request) override;
`)
		}
	}

	restAsyncMethods := getRestAsyncMethods(asyncMethods)
	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  future<$return_type$> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
  future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::GetOperationRequest const& request) override;

  future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<google::cloud::rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::CancelOperationRequest const& request) override;
`)
	}

	p.Print(`
 private:
  std::shared_ptr<$stub_rest_class_name$> child_;
  TracingOptions tracing_options_;
  std::set<std::string> components_;
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateRestLoggingDecoratorCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["logging_rest_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{
		vars["logging_rest_header_path"],
		"google/cloud/internal/log_wrapper.h",
		"google/cloud/status_or.h",
	})
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
$logging_rest_class_name$::$logging_rest_class_name$(
    std::shared_ptr<$stub_rest_class_name$> child,
    TracingOptions tracing_options,
    std::set<std::string> components)
    : child_(std::move(child)), tracing_options_(std::move(tracing_options)),
      components_(std::move(components)) {}
`)

	restMethods := getRestMethods(methods)
	for _, m := range restMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isLongrunning(m) {
			p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
$logging_rest_class_name$::Async$method_name$(
      CompletionQueue& cq,
      std::unique_ptr<rest_internal::RestContext> rest_context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  return google::cloud::internal::LogWrapper(
      [this](CompletionQueue& cq,
             std::unique_ptr<rest_internal::RestContext> rest_context,
             google::cloud::internal::ImmutableOptions options,
             $request_type$ const& request) {
        return child_->Async$method_name$(
            cq, std::move(rest_context), std::move(options), request);
      },
      cq, std::move(rest_context), std::move(options), request, __func__,
      tracing_options_);
}

StatusOr<$response_type$>
$logging_rest_class_name$::$method_name$(
    rest_internal::RestContext& rest_context,
    Options const& options,
    $request_type$ const& request) {
  return google::cloud::internal::LogWrapper(
      [this](rest_internal::RestContext& rest_context,
             Options const& options,
             $request_type$ const& request) {
        return child_->$method_name$(rest_context, options, request);
      },
      rest_context, options, request, __func__, tracing_options_);
}
`)
		} else {
			p.PrintWith(mVars, `
$return_type$
$logging_rest_class_name$::$method_name$(
    rest_internal::RestContext& rest_context,
    Options const& options,
    $request_type$ const& request) {
  return google::cloud::internal::LogWrapper(
      [this](rest_internal::RestContext& rest_context,
             Options const& options,
             $request_type$ const& request) {
        return child_->$method_name$(rest_context, options, request);
      },
      rest_context, options, request, __func__, tracing_options_);
}
`)
		}
	}

	restAsyncMethods := getRestAsyncMethods(asyncMethods)
	for _, m := range restAsyncMethods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
future<$return_type$>
$logging_rest_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  return google::cloud::internal::LogWrapper(
      [this](CompletionQueue& cq,
             std::unique_ptr<rest_internal::RestContext> rest_context,
             google::cloud::internal::ImmutableOptions options,
             $request_type$ const& request) {
        return child_->Async$method_name$(
            cq, std::move(rest_context), std::move(options), request);
      },
      cq, std::move(rest_context), std::move(options), request, __func__,
      tracing_options_);
}
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
$logging_rest_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::GetOperationRequest const& request) {
  return google::cloud::internal::LogWrapper(
      [this](CompletionQueue& cq,
             std::unique_ptr<rest_internal::RestContext> rest_context,
             google::cloud::internal::ImmutableOptions options,
             google::longrunning::GetOperationRequest const& request) {
        return child_->AsyncGetOperation(
            cq, std::move(rest_context), std::move(options), request);
      },
      cq, std::move(rest_context), std::move(options), request, __func__,
      tracing_options_);
}

future<Status>
$logging_rest_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::unique_ptr<rest_internal::RestContext> rest_context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::CancelOperationRequest const& request) {
  return google::cloud::internal::LogWrapper(
      [this](CompletionQueue& cq,
             std::unique_ptr<rest_internal::RestContext> rest_context,
             google::cloud::internal::ImmutableOptions options,
             google::longrunning::CancelOperationRequest const& request) {
        return child_->AsyncCancelOperation(
            cq, std::move(rest_context), std::move(options), request);
      },
      cq, std::move(rest_context), std::move(options), request, __func__,
      tracing_options_);
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	return filepath.Clean(ccPath), p.String()
}
