// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"fmt"
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateForwardingClientHeader(_ *api.Service, serviceVars map[string]string, _ *config.Library) (string, string) {
	headerPath := serviceVars["forwarding_client_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["forwarding_connection_header_path"],
		vars["client_header_path"],
	})

	comment := fmt.Sprintf(`/// @deprecated This namespace exists for backwards compatibility. Use the
///     types defined in %s instead of the aliases defined in
///     this namespace.`, vars["product_namespace"])
	p.HeaderOpenForwardingNamespaces(vars["forwarding_namespace"], comment)

	p.Print(`
/// @deprecated Use $product_namespace$::$client_class_name$ directly.
using ::google::cloud::$product_namespace$::$client_class_name$;
`)

	p.HeaderCloseNamespaces(vars["forwarding_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateForwardingConnectionHeader(_ *api.Service, serviceVars map[string]string, _ *config.Library) (string, string) {
	headerPath := serviceVars["forwarding_connection_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["forwarding_idempotency_policy_header_path"],
		vars["connection_header_path"],
	})

	p.HeaderOpenForwardingNamespaces(vars["forwarding_namespace"], "")

	p.Print(`
/// @deprecated Use $product_namespace$::Make$connection_class_name$ directly.
using ::google::cloud::$product_namespace$::Make$connection_class_name$;

/// @deprecated Use $product_namespace$::$connection_class_name$ directly.
using ::google::cloud::$product_namespace$::$connection_class_name$;

/// @deprecated Use $product_namespace$::$limited_error_count_retry_policy_name$ directly.
using ::google::cloud::$product_namespace$::$limited_error_count_retry_policy_name$;

/// @deprecated Use $product_namespace$::$limited_time_retry_policy_name$ directly.
using ::google::cloud::$product_namespace$::$limited_time_retry_policy_name$;

/// @deprecated Use $product_namespace$::$retry_policy_name$ directly.
using ::google::cloud::$product_namespace$::$retry_policy_name$;
`)

	p.HeaderCloseNamespaces(vars["forwarding_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateForwardingIdempotencyPolicyHeader(_ *api.Service, serviceVars map[string]string, _ *config.Library) (string, string) {
	headerPath := serviceVars["forwarding_idempotency_policy_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["idempotency_policy_header_path"],
	})

	p.HeaderOpenForwardingNamespaces(vars["forwarding_namespace"], "")

	p.Print(`
/// @deprecated Use $product_namespace$::MakeDefault$idempotency_class_name$ directly.
using ::google::cloud::$product_namespace$::MakeDefault$idempotency_class_name$;

/// @deprecated Use $product_namespace$::$idempotency_class_name$ directly.
using ::google::cloud::$product_namespace$::$idempotency_class_name$;
`)

	p.HeaderCloseNamespaces(vars["forwarding_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateForwardingMockConnectionHeader(_ *api.Service, serviceVars map[string]string, _ *config.Library) (string, string) {
	headerPath := serviceVars["forwarding_mock_connection_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["forwarding_connection_header_path"],
		vars["mock_connection_header_path"],
	})

	comment := fmt.Sprintf(`/// @deprecated This namespace exists for backwards compatibility. Use the
///     types defined in %s instead of the aliases
///     defined in this namespace.`, vars["product_mocks_namespace"])
	p.HeaderOpenForwardingNamespaces(vars["forwarding_mocks_namespace"], comment)

	p.Print(`
/// @deprecated Use $product_mocks_namespace$::$mock_connection_class_name$ directly.
using ::google::cloud::$product_mocks_namespace$::$mock_connection_class_name$;
`)

	p.HeaderCloseNamespaces(vars["forwarding_mocks_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateForwardingOptionsHeader(_ *api.Service, serviceVars map[string]string, methods []*api.Method, _ *config.Library) (string, string) {
	headerPath := serviceVars["forwarding_options_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["forwarding_connection_header_path"],
		vars["forwarding_idempotency_policy_header_path"],
		vars["options_header_path"],
	})

	p.HeaderOpenForwardingNamespaces(vars["forwarding_namespace"], "")

	if hasLongrunningMethod(methods) {
		p.Print(`
/// @deprecated Use $product_namespace$::$service_name$PollingPolicyOption directly.
using ::google::cloud::$product_namespace$::$service_name$PollingPolicyOption;
`)
	}

	p.Print(`
/// @deprecated Use $product_namespace$::$service_name$BackoffPolicyOption directly.
using ::google::cloud::$product_namespace$::$service_name$BackoffPolicyOption;

/// @deprecated Use $product_namespace$::$service_name$ConnectionIdempotencyPolicyOption directly.
using ::google::cloud::$product_namespace$::$service_name$ConnectionIdempotencyPolicyOption;

/// @deprecated Use $product_namespace$::$service_name$PolicyOptionList directly.
using ::google::cloud::$product_namespace$::$service_name$PolicyOptionList;

/// @deprecated Use $product_namespace$::$service_name$RetryPolicyOption directly.
using ::google::cloud::$product_namespace$::$service_name$RetryPolicyOption;
`)

	p.HeaderCloseNamespaces(vars["forwarding_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}
