// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateAuthDecoratorHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["auth_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_header_path"],
		"google/cloud/internal/unified_grpc_credentials.h",
		"google/cloud/version.h",
	})
	if hasLongrunningMethod(methods) {
		p.ProtobufIncludes([]string{"google/longrunning/operations.grpc.pb.h"})
	}
	p.SystemIncludes([]string{"memory", "set", "string"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $auth_class_name$ : public $stub_class_name$ {
 public:
  ~$auth_class_name$() override = default;
  $auth_class_name$(
      std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth,
      std::shared_ptr<$stub_class_name$> child);
`)

	printDecoratorPublicMethods(p, svc, methods, asyncMethods, vars, lib, model)

	p.Print(`
 private:
  std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth_;
  std::shared_ptr<$stub_class_name$> child_;
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateAuthDecoratorCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["auth_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	localIncludes := []string{vars["auth_header_path"]}
	if hasBidiStreamingMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_read_write_stream_auth.h")
	}
	if hasAsynchronousStreamingReadMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_streaming_read_rpc_auth.h")
	}
	if hasAsynchronousStreamingWriteMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_streaming_write_rpc_auth.h")
	}
	if hasStreamingWriteMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/streaming_write_rpc_impl.h")
	}
	p.CcLocalIncludes(localIncludes)

	if vars["proto_grpc_header_path"] != "" {
		p.ProtobufIncludes([]string{vars["proto_grpc_header_path"]})
	}
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
$auth_class_name$::$auth_class_name$(
    std::shared_ptr<google::cloud::internal::GrpcAuthenticationStrategy> auth,
    std::shared_ptr<$stub_class_name$> child)
    : auth_(std::move(auth)), child_(std::move(child)) {}
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::internal::StreamingWriteRpc<
    $request_type$,
    $response_type$>>
$auth_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const& options) {
  using ErrorStream = ::google::cloud::internal::StreamingWriteRpcError<
      $request_type$, $response_type$>;
  auto status = auth_->ConfigureContext(*context);
  if (!status.ok()) return std::make_unique<ErrorStream>(std::move(status));
  return child_->$method_name$(std::move(context), options);
}
`)
			continue
		}
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$auth_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  using StreamAuth = google::cloud::internal::AsyncStreamingReadWriteRpcAuth<
    $request_type$, $response_type$>;

  auto call = [child = child_, cq, options = std::move(options)](
                  std::shared_ptr<grpc::ClientContext> ctx) {
    return child->Async$method_name$(cq, std::move(ctx), options);
  };
  return std::make_unique<StreamAuth>(
    std::move(context), auth_, StreamAuth::StreamFactory(std::move(call)));
}
`)
			continue
		}
		if isLongrunning(m) {
			p.PrintWith(mVars, `
future<StatusOr<google::longrunning::Operation>>
$auth_class_name$::Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  return auth_->AsyncConfigureContext(std::move(context)).then(
      [cq, child = child_, options = std::move(options), request](
          future<StatusOr<std::shared_ptr<grpc::ClientContext>>> f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->Async$method_name$(
            cq, *std::move(context), std::move(options), request);
      });
}

StatusOr<google::longrunning::Operation>
$auth_class_name$::$method_name$(
      grpc::ClientContext& context,
      Options options,
      $request_type$ const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->$method_name$(context, options, request);
}
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::StreamingReadRpc<$response_type$>>
$auth_class_name$::$method_name$(
   std::shared_ptr<grpc::ClientContext> context,
   Options const& options,
   $request_type$ const& request) {
  using ErrorStream = ::google::cloud::internal::StreamingReadRpcError<
      $response_type$>;
  auto status = auth_->ConfigureContext(*context);
  if (!status.ok()) return std::make_unique<ErrorStream>(std::move(status));
  return child_->$method_name$(std::move(context), options, request);
}
`)
			continue
		}
		p.PrintWith(mVars, `
$return_type$ $auth_class_name$::$method_name$(
    grpc::ClientContext& context,
    Options const& options,
    $request_type$ const& request) {
  auto status = auth_->ConfigureContext(context);
  if (!status.ok()) return status;
  return child_->$method_name$(context, options, request);
}
`)
	}

	for _, m := range asyncMethods {
		if isBidiStreaming(m) || isLongrunning(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::internal::AsyncStreamingReadRpc<
    $response_type$>>
$auth_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  using StreamAuth = google::cloud::internal::AsyncStreamingReadRpcAuth<
    $response_type$>;

  auto& child = child_;
  auto call = [child, cq, opts = std::move(options), request](std::shared_ptr<grpc::ClientContext> ctx) {
    return child->Async$method_name$(cq, std::move(ctx), opts, request);
  };
  return std::make_unique<StreamAuth>(
    std::move(context), auth_, StreamAuth::StreamFactory(std::move(call)));
}
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::internal::AsyncStreamingWriteRpc<
    $request_type$, $response_type$>>
$auth_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  using StreamAuth = google::cloud::internal::AsyncStreamingWriteRpcAuth<
    $request_type$, $response_type$>;

  auto call = [child = child_, cq, options = std::move(options)](
                  std::shared_ptr<grpc::ClientContext> ctx) {
    return child->Async$method_name$(cq, std::move(ctx), options);
  };
  return std::make_unique<StreamAuth>(
    std::move(context), auth_, StreamAuth::StreamFactory(std::move(call)));
}
`)
			continue
		}
		if isResponseTypeEmpty(m) {
			p.PrintWith(mVars, `
future<Status>
$auth_class_name$::Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  return auth_->AsyncConfigureContext(std::move(context)).then(
      [cq, child = child_, options = std::move(options), request](
          future<StatusOr<std::shared_ptr<grpc::ClientContext>>> f) mutable {
        auto context = f.get();
        if (!context) return make_ready_future(std::move(context).status());
        return child->Async$method_name$(
            cq, *std::move(context), std::move(options), request);
      });
}
`)
			continue
		}
		p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
$auth_class_name$::Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) {
  return auth_->AsyncConfigureContext(std::move(context)).then(
      [cq, child = child_, options = std::move(options), request](
          future<StatusOr<std::shared_ptr<grpc::ClientContext>>> f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(StatusOr<$response_type$>(
              std::move(context).status()));
        }
        return child->Async$method_name$(
            cq, *std::move(context), std::move(options), request);
      });
}
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
$auth_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::GetOperationRequest const& request) {
  using ReturnType = StatusOr<google::longrunning::Operation>;
  return auth_->AsyncConfigureContext(std::move(context)).then(
      [cq, child = child_, options = std::move(options), request](
          future<StatusOr<std::shared_ptr<grpc::ClientContext>>> f) mutable {
        auto context = f.get();
        if (!context) {
          return make_ready_future(ReturnType(std::move(context).status()));
        }
        return child->AsyncGetOperation(
            cq, *std::move(context), std::move(options), request);
      });
}

future<Status> $auth_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::CancelOperationRequest const& request) {
  return auth_->AsyncConfigureContext(std::move(context)).then(
      [cq, child = child_, options = std::move(options), request](
          future<StatusOr<std::shared_ptr<grpc::ClientContext>>> f) mutable {
        auto context = f.get();
        if (!context) return make_ready_future(std::move(context).status());
        return child->AsyncCancelOperation(
            cq, *std::move(context), std::move(options), request);
      });
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
