// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"
	"slices"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func isLongrunningMetadataTypeUsedAsResponse(m *api.Method) bool {
	if m.OperationInfo == nil {
		return false
	}
	return m.OperationInfo.ResponseTypeID == "google.protobuf.Empty" || m.OperationInfo.ResponseTypeID == ".google.protobuf.Empty"
}

func hasRequestIDService(methods []*api.Method) bool {
	return slices.ContainsFunc(methods, hasRequestID)
}

func generateConnectionImplHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["connection_impl_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	var localIncludes []string
	localIncludes = append(localIncludes,
		vars["idempotency_policy_header_path"],
		vars["options_header_path"],
		vars["stub_header_path"],
		vars["connection_header_path"],
		vars["retry_traits_header_path"],
		"google/cloud/background_threads.h",
		"google/cloud/backoff_policy.h",
		"google/cloud/options.h",
		"google/cloud/status_or.h",
		"google/cloud/version.h",
	)
	if hasBidiStreamingMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/async_streaming_read_write_rpc.h")
	}
	if hasLongrunningMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/future.h", "google/cloud/polling_policy.h")
	}
	if hasRequestIDService(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/invocation_id_generator.h")
	}
	if hasStreamingReadMethod(methods) || hasPaginatedMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/stream_range.h")
	}
	p.HeaderLocalIncludes(localIncludes)

	if hasLongrunningMethod(methods) {
		p.ProtobufIncludes([]string{"google/longrunning/operations.grpc.pb.h"})
	}
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	for _, m := range methods {
		if isStreamingRead(m) {
			mVars := buildMethodVars(svc, m, vars, lib, model)
			p.PrintWith(mVars, `
void $service_name$$method_name$StreamingUpdater(
    $response_type$ const& response,
    $request_type$& request);
`)
		}
	}

	p.Print(`
class $connection_class_name$Impl
    : public $product_namespace$::$connection_class_name$ {
 public:
  ~$connection_class_name$Impl() override = default;

  $connection_class_name$Impl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<$product_internal_namespace$::$stub_class_name$> stub,
    Options options);

  Options options() override { return options_; }
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
      $request_type$,
      $response_type$>>
  Async$method_name$() override;
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  StreamRange<$response_type$>
  $method_name$($request_type$ const& request) override;
`)
			continue
		}
		if isStreamingWrite(m) {
			continue
		}
		if isPaginated(m) {
			p.PrintWith(mVars, `
  StreamRange<$range_output_type$>
  $method_name$($request_type$ request) override;
`)
			continue
		}
		if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
  future<Status>
  $method_name$($request_type$ const& request) override;

  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag,
      $request_type$ const& request) override;

  future<Status>
  $method_name$(
      $longrunning_operation_type$ const& operation) override;
`)
			} else {
				p.PrintWith(mVars, `
  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($request_type$ const& request) override;

  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag,
      $request_type$ const& request) override;

  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$(
      $longrunning_operation_type$ const& operation) override;
`)
			}
			continue
		}
		p.PrintWith(mVars, `
  $return_type$
  $method_name$($request_type$ const& request) override;
`)
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  future<$return_type$>
  Async$method_name$($request_type$ const& request) override;
`)
	}

	p.Print(`
 private:
  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<$product_internal_namespace$::$stub_class_name$> stub_;
  Options options_;`)

	if hasRequestIDService(methods) {
		p.Print(`
  std::shared_ptr<google::cloud::internal::InvocationIdGenerator>
      invocation_id_generator_ =
          std::make_shared<google::cloud::internal::InvocationIdGenerator>();`)
	}

	p.Print(`
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateConnectionImplCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["connection_impl_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	var localIncludes []string
	localIncludes = append(localIncludes,
		vars["connection_impl_header_path"],
		vars["option_defaults_header_path"],
		"google/cloud/background_threads.h",
		"google/cloud/common_options.h",
		"google/cloud/grpc_options.h",
		"google/cloud/internal/retry_loop.h",
	)
	if hasPaginatedMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/pagination_range.h")
	}
	if hasLongrunningMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_long_running_operation.h")
	}
	if len(asyncMethods) > 0 {
		localIncludes = append(localIncludes, "google/cloud/internal/async_retry_loop.h")
	}
	if hasStreamingReadMethod(methods) {
		localIncludes = append(localIncludes,
			"google/cloud/internal/resumable_streaming_read_rpc.h",
			"google/cloud/internal/streaming_read_rpc_logging.h",
		)
	}
	p.CcLocalIncludes(localIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`namespace {

std::unique_ptr<$product_namespace$::$retry_policy_name$>
retry_policy(Options const& options) {
  return options.get<$product_namespace$::$retry_policy_name$Option>()->clone();
}

std::unique_ptr<BackoffPolicy>
backoff_policy(Options const& options) {
  return options.get<$product_namespace$::$service_name$BackoffPolicyOption>()->clone();
}

std::unique_ptr<$product_namespace$::$idempotency_class_name$>
idempotency_policy(Options const& options) {
  return options.get<$product_namespace$::$idempotency_class_name$Option>()->clone();
}
`)

	if hasLongrunningMethod(methods) {
		p.Print(`
std::unique_ptr<PollingPolicy> polling_policy(Options const& options) {
  return options.get<$product_namespace$::$service_name$PollingPolicyOption>()->clone();
}
`)
	}

	p.Print(`
} // namespace
`)

	for _, m := range methods {
		if isStreamingRead(m) {
			mVars := buildMethodVars(svc, m, vars, lib, model)
			p.PrintWith(mVars, `
void $service_name$$method_name$StreamingUpdater(
    $response_type$ const&,
    $request_type$&) {}
`)
		}
	}

	p.Print(`
$connection_class_name$Impl::$connection_class_name$Impl(
    std::unique_ptr<google::cloud::BackgroundThreads> background,
    std::shared_ptr<$product_internal_namespace$::$stub_class_name$> stub,
    Options options)
  : background_(std::move(background)), stub_(std::move(stub)),
    options_(internal::MergeOptions(
        std::move(options),
        $connection_class_name$::options())) {}
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$connection_class_name$Impl::Async$method_name$() {
  return stub_->Async$method_name$(background_->cq(),
                                std::make_shared<grpc::ClientContext>(),
                                internal::SaveCurrentOptions());
}
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
StreamRange<$response_type$>
$connection_class_name$Impl::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto factory = [stub = stub_, current]($request_type$ const& request) {
    return stub->$method_name$(
        std::make_shared<grpc::ClientContext>(), *current, request);
  };
  auto resumable =
      internal::MakeResumableStreamingReadRpc<$response_type$, $request_type$>(
          retry_policy(*current), backoff_policy(*current), factory,
          $service_name$$method_name$StreamingUpdater, request);
  return internal::MakeStreamRange<$response_type$>(
      [resumable = std::move(resumable)]()
          -> absl::variant<
              Status,
              $response_type$> {
        $response_type$ response;
        auto status = resumable->Read(&response);
        if (status.has_value()) return *status;
        return response;
      });
}
`)
			continue
		}
		if isStreamingWrite(m) {
			continue
		}
		if isPaginated(m) {
			p.PrintWith(mVars, `
StreamRange<$range_output_type$>
$connection_class_name$Impl::$method_name$($request_type$ request) {
  request.clear_page_token();
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto idempotency = idempotency_policy(*current)->$method_name$(request);
  char const* function_name = __func__;
  return google::cloud::internal::MakePaginationRange<StreamRange<$range_output_type$>>(
      current, std::move(request),
      [idempotency, function_name, stub = stub_,
       retry = std::shared_ptr<$product_namespace$::$retry_policy_name$>(retry_policy(*current)),
       backoff = std::shared_ptr<BackoffPolicy>(backoff_policy(*current))](
          Options const& options, $request_type$ const& r) {
        return google::cloud::internal::RetryLoop(
            retry->clone(), backoff->clone(), idempotency,
            [stub](grpc::ClientContext& context, Options const& options,
                   $request_type$ const& request) {
              return stub->$method_name$(context, options, request);
            },
            options, r, function_name);
      },
      []($response_type$ r) {
        std::vector<$range_output_type$> result(r.$range_output_field_name$().size());
        auto& messages = *r.mutable_$range_output_field_name$();
        std::move(messages.begin(), messages.end(), result.begin());
        return result;
      });
}
`)
			continue
		}
		if isLongrunning(m) {
			returnFragment := "future<StatusOr<" + mVars["longrunning_deduced_response_type"] + ">>"
			if isResponseTypeEmpty(m) {
				returnFragment = "future<Status>"
			}

			requestIdFragment := ""
			if hasRequestID(m) {
				requestIdFragment = `
  if (request_copy.` + mVars["request_id_field_name"] + `().empty()) {
    request_copy.set_` + mVars["request_id_field_name"] + `(invocation_id_generator_->MakeInvocationId());
  }`
			}

			extractValueFragment := "    &google::cloud::internal::ExtractLongRunningResultResponse<" + mVars["longrunning_deduced_response_type"] + ">,"
			if isLongrunningMetadataTypeUsedAsResponse(m) {
				extractValueFragment = "    &google::cloud::internal::ExtractLongRunningResultMetadata<" + mVars["longrunning_deduced_response_type"] + ">,"
			}

			elideProtobufEmptyFragment := ""
			if isResponseTypeEmpty(m) {
				elideProtobufEmptyFragment = `
    .then([](future<StatusOr<google::protobuf::Empty>> f) {
      return f.get().status();
    }))`
			}

			mVars["lro_return_fragment"] = returnFragment
			mVars["lro_request_id_fragment"] = requestIdFragment
			mVars["lro_extract_value_fragment"] = extractValueFragment
			mVars["lro_elide_fragment"] = elideProtobufEmptyFragment

			p.PrintWith(mVars, `
$lro_return_fragment$
$connection_class_name$Impl::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto request_copy = request;$lro_request_id_fragment$
  auto const idempotent =
      idempotency_policy(*current)->$method_name$(request_copy);
  return google::cloud::internal::AsyncLongRunningOperation<$longrunning_deduced_response_type$>(
    background_->cq(), current, std::move(request_copy),
    [stub = stub_](google::cloud::CompletionQueue& cq,
                   std::shared_ptr<grpc::ClientContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   $request_type$ const& request) {
     return stub->Async$method_name$(
         cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](google::cloud::CompletionQueue& cq,
                   std::shared_ptr<grpc::ClientContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::GetOperationRequest const& request) {
     return stub->AsyncGetOperation(
         cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](google::cloud::CompletionQueue& cq,
                   std::shared_ptr<grpc::ClientContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::CancelOperationRequest const& request) {
     return stub->AsyncCancelOperation(
         cq, std::move(context), std::move(options), request);
    },
$lro_extract_value_fragment$
    retry_policy(*current), backoff_policy(*current), idempotent,
    polling_policy(*current), __func__)$lro_elide_fragment$;
}

StatusOr<$longrunning_operation_type$>
$connection_class_name$Impl::$method_name$(
      NoAwaitTag, $request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::internal::RetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->$method_name$(request),
      [this](
          grpc::ClientContext& context, Options const& options,
          $request_type$ const& request) {
        return stub_->$method_name$(context, options, request);
      },
      *current, request, __func__);
}

$lro_return_fragment$
$connection_class_name$Impl::$method_name$(
      $longrunning_operation_type$ const& operation) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  if (!operation.metadata().Is<typename $longrunning_metadata_type$>()) {
    return make_ready_$lro_return_fragment$(
        internal::InvalidArgumentError("operation does not correspond to $method_name$",
                                       GCP_ERROR_INFO().WithMetadata("operation", operation.metadata().DebugString())));
  }

  return google::cloud::internal::AsyncAwaitLongRunningOperation<$longrunning_deduced_response_type$>(
    background_->cq(), current, operation,
    [stub = stub_](google::cloud::CompletionQueue& cq,
                   std::shared_ptr<grpc::ClientContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::GetOperationRequest const& request) {
     return stub->AsyncGetOperation(
         cq, std::move(context), std::move(options), request);
    },
    [stub = stub_](google::cloud::CompletionQueue& cq,
                   std::shared_ptr<grpc::ClientContext> context,
                   google::cloud::internal::ImmutableOptions options,
                   google::longrunning::CancelOperationRequest const& request) {
     return stub->AsyncCancelOperation(
         cq, std::move(context), std::move(options), request);
    },
$lro_extract_value_fragment$
    polling_policy(*current), __func__)$lro_elide_fragment$;
}
`)
			continue
		}

		if hasRequestID(m) {
			p.PrintWith(mVars, `
$return_type$
$connection_class_name$Impl::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto request_copy = request;
  if (request_copy.$request_id_field_name$().empty()) {
    request_copy.set_$request_id_field_name$(invocation_id_generator_->MakeInvocationId());
  }
  return google::cloud::internal::RetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->$method_name$(request_copy),
      [this](grpc::ClientContext& context, Options const& options,
             $request_type$ const& request) {
        return stub_->$method_name$(context, options, request);
      },
      *current, request_copy, __func__);
}
`)
			continue
		}

		p.PrintWith(mVars, `
$return_type$
$connection_class_name$Impl::$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  return google::cloud::internal::RetryLoop(
      retry_policy(*current), backoff_policy(*current),
      idempotency_policy(*current)->$method_name$(request),
      [this](grpc::ClientContext& context, Options const& options,
             $request_type$ const& request) {
        return stub_->$method_name$(context, options, request);
      },
      *current, request, __func__);
}
`)
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		requestIdFragment := ""
		if hasRequestID(m) {
			requestIdFragment = `
  if (request_copy.` + mVars["request_id_field_name"] + `().empty()) {
    request_copy.set_` + mVars["request_id_field_name"] + `(invocation_id_generator_->MakeInvocationId());
  }`
		}
		mVars["async_request_id_fragment"] = requestIdFragment

		p.PrintWith(mVars, `
future<$return_type$>
$connection_class_name$Impl::Async$method_name$($request_type$ const& request) {
  auto current = google::cloud::internal::SaveCurrentOptions();
  auto request_copy = request;$async_request_id_fragment$
  auto const idempotent =
      idempotency_policy(*current)->$method_name$(request_copy);
  auto retry = retry_policy(*current);
  auto backoff = backoff_policy(*current);
  return google::cloud::internal::AsyncRetryLoop(
      std::move(retry), std::move(backoff), idempotent, background_->cq(),
      [stub = stub_](CompletionQueue& cq,
                     std::shared_ptr<grpc::ClientContext> context,
                     google::cloud::internal::ImmutableOptions options,
                     $request_type$ const& request) {
        return stub->Async$method_name$(
            cq, std::move(context), std::move(options), request);
      },
      std::move(current), std::move(request_copy), __func__);
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	return filepath.Clean(ccPath), p.String()
}
