// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"fmt"
	"maps"
	"path/filepath"
	"slices"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

type mixinStubInfo struct {
	stubName string
	stubFQN  string
	header   string
}

func getMixinStubs(svc *api.Service, methods []*api.Method) []mixinStubInfo {
	wellKnown := []struct {
		id       string
		stubName string
		stubFQN  string
		header   string
	}{
		{
			id:       ".google.longrunning.Operations",
			stubName: "operations_stub",
			stubFQN:  "google::longrunning::Operations",
			header:   "google/longrunning/operations.grpc.pb.h",
		},
		{
			id:       ".google.iam.v1.IAMPolicy",
			stubName: "iampolicy_stub",
			stubFQN:  "google::iam::v1::IAMPolicy",
			header:   "google/iam/v1/iam_policy.grpc.pb.h",
		},
		{
			id:       ".google.cloud.location.Locations",
			stubName: "locations_stub",
			stubFQN:  "google::cloud::location::Locations",
			header:   "google/cloud/location/locations.grpc.pb.h",
		},
	}

	seen := make(map[string]bool)
	for _, m := range methods {
		if m.SourceService != nil && m.SourceService.ID != svc.ID {
			seen[m.SourceService.ID] = true
		}
	}

	var result []mixinStubInfo
	for _, wk := range wellKnown {
		if seen[wk.id] {
			result = append(result, mixinStubInfo{
				stubName: wk.stubName,
				stubFQN:  wk.stubFQN,
				header:   wk.header,
			})
		}
	}
	return result
}

func generateStubHeader(svc *api.Service, serviceVars map[string]string, methods []*api.Method, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["stub_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	hasAsync := len(asyncMethods) > 0 || hasLongrunningMethod(methods)
	needsCompletionQueue := hasAsync || hasBidiStreamingMethod(methods)

	var localIncludes []string
	if hasBidiStreamingMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/async_streaming_read_write_rpc.h")
	}
	if needsCompletionQueue {
		localIncludes = append(localIncludes, "google/cloud/completion_queue.h")
	}
	if hasAsync {
		localIncludes = append(localIncludes, "google/cloud/future.h")
	}
	if hasAsynchronousStreamingReadMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_streaming_read_rpc.h")
	}
	if hasAsynchronousStreamingWriteMethod(asyncMethods) {
		localIncludes = append(localIncludes, "google/cloud/internal/async_streaming_write_rpc.h")
	}
	if hasStreamingReadMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/streaming_read_rpc.h")
	}
	if hasStreamingWriteMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/streaming_write_rpc.h")
	}
	localIncludes = append(localIncludes,
		"google/cloud/options.h",
		"google/cloud/status_or.h",
		"google/cloud/version.h",
	)
	p.HeaderLocalIncludes(localIncludes)

	var additionalPb []string
	if vars["additional_pb_header_paths"] != "" {
		for h := range strings.SplitSeq(vars["additional_pb_header_paths"], ",") {
			if h != "" {
				additionalPb = append(additionalPb, h)
			}
		}
	}
	p.ProtobufIncludes(additionalPb)

	allMixins := getMixinStubs(svc, methods)
	var mixinHeaders []string
	for _, mixin := range allMixins {
		if mixin.header != "" {
			mixinHeaders = append(mixinHeaders, mixin.header)
		}
	}
	p.ProtobufIncludes(mixinHeaders)

	var mainPb []string
	if vars["proto_grpc_header_path"] != "" {
		mainPb = append(mainPb, vars["proto_grpc_header_path"])
	}
	includeLroHeader := hasLongrunningMethod(methods) && !slices.Contains(mixinHeaders, "google/longrunning/operations.grpc.pb.h")
	if includeLroHeader {
		mainPb = append(mainPb, "google/longrunning/operations.grpc.pb.h")
	}
	p.ProtobufIncludes(mainPb)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $stub_class_name$ {
 public:
  virtual ~$stub_class_name$() = 0;
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
  virtual std::unique_ptr<::google::cloud::internal::StreamingWriteRpc<
      $request_type$,
      $response_type$>>
  $method_name$(
      std::shared_ptr<grpc::ClientContext> context,
      Options const& options) = 0;
`)
			continue
		}
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
  virtual std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
      $request_type$,
      $response_type$>>
  Async$method_name$(
      google::cloud::CompletionQueue const& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options) = 0;
`)
			continue
		}
		if isLongrunning(m) {
			p.PrintWith(mVars, `
  virtual future<StatusOr<google::longrunning::Operation>> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) = 0;

  virtual StatusOr<google::longrunning::Operation> $method_name$(
      grpc::ClientContext& context,
      Options options,
      $request_type$ const& request) = 0;
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  virtual std::unique_ptr<google::cloud::internal::StreamingReadRpc<$response_type$>>
  $method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const& options,
    $request_type$ const& request) = 0;
`)
			continue
		}
		p.PrintWith(mVars, `
  virtual $return_type$ $method_name$(
      grpc::ClientContext& context,
      Options const& options,
      $request_type$ const& request) = 0;
`)
	}

	for _, m := range asyncMethods {
		if isBidiStreaming(m) || isLongrunning(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  virtual std::unique_ptr<::google::cloud::internal::AsyncStreamingReadRpc<
      $response_type$>>
  Async$method_name$(
      google::cloud::CompletionQueue const& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) = 0;
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
  virtual std::unique_ptr<::google::cloud::internal::AsyncStreamingWriteRpc<
      $request_type$, $response_type$>>
  Async$method_name$(
      google::cloud::CompletionQueue const& cq,
      std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) = 0;
`)
			continue
		}
		p.PrintWith(mVars, `
  virtual future<$return_type$>
  Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) = 0;
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
  virtual future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
      google::longrunning::GetOperationRequest const& request) = 0;

  virtual future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::CancelOperationRequest const& request) = 0;
`)
	}

	p.Print(`};

class Default$stub_class_name$ : public $stub_class_name$ {
 public:`)

	// Constructor
	hasLro := hasLongrunningMethod(methods)
	var filteredMixins []mixinStubInfo
	for _, mixin := range allMixins {
		if hasLro && mixin.stubName == "operations_stub" {
			continue
		}
		filteredMixins = append(filteredMixins, mixin)
	}

	if hasLro {
		p.Print(`
  Default$stub_class_name$(
      std::unique_ptr<$grpc_stub_fqn$::StubInterface> grpc_stub,
`)
		for _, mixin := range filteredMixins {
			p.Print(fmt.Sprintf("      std::unique_ptr<%s::StubInterface> %s,\n", mixin.stubFQN, mixin.stubName))
		}
		p.Print(`      std::unique_ptr<google::longrunning::Operations::StubInterface> operations_stub)
      : grpc_stub_(std::move(grpc_stub)),
`)
		for _, mixin := range filteredMixins {
			p.Print(fmt.Sprintf("        %s_(std::move(%s)),\n", mixin.stubName, mixin.stubName))
		}
		p.Print(`        operations_stub_(std::move(operations_stub)) {}
`)
	} else {
		if len(filteredMixins) == 0 {
			p.Print(`
  explicit Default$stub_class_name$(
      std::unique_ptr<$grpc_stub_fqn$::StubInterface> grpc_stub)
      : grpc_stub_(std::move(grpc_stub)) {}
`)
		} else {
			p.Print(`
  explicit Default$stub_class_name$(
      std::unique_ptr<$grpc_stub_fqn$::StubInterface> grpc_stub`)
			for _, mixin := range filteredMixins {
				p.Print(fmt.Sprintf(`,
      std::unique_ptr<%s::StubInterface> %s
`, mixin.stubFQN, mixin.stubName))
			}
			p.Print(`)
      : grpc_stub_(std::move(grpc_stub))`)
			for _, mixin := range filteredMixins {
				p.Print(fmt.Sprintf(`,
        %s_(std::move(%s))`, mixin.stubName, mixin.stubName))
			}
			p.Print(` {}
`)
		}
	}

	// Public methods for Default*Stub
	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<::google::cloud::internal::StreamingWriteRpc<
      $request_type$,
      $response_type$>>
  $method_name$(
      std::shared_ptr<grpc::ClientContext> context,
      Options const& options) override;
`)
			continue
		}
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
      $request_type$,
      $response_type$>>
  Async$method_name$(
      google::cloud::CompletionQueue const& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options) override;
`)
			continue
		}
		if isLongrunning(m) {
			p.PrintWith(mVars, `
  future<StatusOr<google::longrunning::Operation>> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;

  StatusOr<google::longrunning::Operation> $method_name$(
      grpc::ClientContext& context,
      Options options,
      $request_type$ const& request) override;
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<google::cloud::internal::StreamingReadRpc<$response_type$>>
  $method_name$(
      std::shared_ptr<grpc::ClientContext> context,
      Options const& options,
      $request_type$ const& request) override;
`)
			continue
		}
		p.PrintWith(mVars, `
  $return_type$ $method_name$(
      grpc::ClientContext& context,
      Options const& options,
      $request_type$ const& request) override;
`)
	}

	for _, m := range asyncMethods {
		if isBidiStreaming(m) || isLongrunning(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<::google::cloud::internal::AsyncStreamingReadRpc<
      $response_type$>>
  Async$method_name$(
      google::cloud::CompletionQueue const& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<::google::cloud::internal::AsyncStreamingWriteRpc<
      $request_type$, $response_type$>>
  Async$method_name$(
      google::cloud::CompletionQueue const& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options) override;
`)
			continue
		}
		p.PrintWith(mVars, `
  future<$return_type$> Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      $request_type$ const& request) override;
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
  future<StatusOr<google::longrunning::Operation>> AsyncGetOperation(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::GetOperationRequest const& request) override;

  future<Status> AsyncCancelOperation(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions options,
      google::longrunning::CancelOperationRequest const& request) override;
`)
	}

	p.Print(`
 private:
  std::unique_ptr<$grpc_stub_fqn$::StubInterface> grpc_stub_;
`)
	for _, mixin := range filteredMixins {
		p.Print(fmt.Sprintf("  std::unique_ptr<%s::StubInterface> %s_;\n", mixin.stubFQN, mixin.stubName))
	}
	if hasLro {
		p.Print("  std::unique_ptr<google::longrunning::Operations::StubInterface> operations_stub_;\n")
	}
	p.Print(`};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateStubCc(svc *api.Service, serviceVars map[string]string, methods []*api.Method, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["stub_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	var ccLocalIncludes = []string{
		vars["stub_header_path"],
		"google/cloud/grpc_error_delegate.h",
		"google/cloud/status_or.h",
	}
	if hasBidiStreamingMethod(methods) {
		ccLocalIncludes = append(ccLocalIncludes, "google/cloud/internal/async_read_write_stream_impl.h")
	}
	if hasAsynchronousStreamingReadMethod(asyncMethods) {
		ccLocalIncludes = append(ccLocalIncludes, "google/cloud/internal/async_streaming_read_rpc_impl.h")
	}
	if hasAsynchronousStreamingWriteMethod(asyncMethods) {
		ccLocalIncludes = append(ccLocalIncludes, "google/cloud/internal/async_streaming_write_rpc_impl.h")
	}
	if hasStreamingWriteMethod(methods) {
		ccLocalIncludes = append(ccLocalIncludes, "google/cloud/internal/streaming_write_rpc_impl.h")
	}
	p.CcLocalIncludes(ccLocalIncludes)

	var pbIncludes []string
	if vars["proto_grpc_header_path"] != "" {
		pbIncludes = append(pbIncludes, vars["proto_grpc_header_path"])
	}
	if hasLongrunningMethod(methods) {
		pbIncludes = append(pbIncludes, "google/longrunning/operations.grpc.pb.h")
	}
	p.ProtobufIncludes(pbIncludes)
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
$stub_class_name$::~$stub_class_name$() = default;
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::internal::StreamingWriteRpc<
    $request_type$,
    $response_type$>>
Default$stub_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const&) {
  auto response = std::make_unique<$response_type$>();
  auto stream = $grpc_stub$->$method_name$(context.get(), response.get());
  return std::make_unique<::google::cloud::internal::StreamingWriteRpcImpl<
      $request_type$, $response_type$>>(
    std::move(context), std::move(response), std::move(stream));
}
`)
			continue
		}
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
Default$stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  return google::cloud::internal::MakeStreamingReadWriteRpc<$request_type$, $response_type$>(
      cq, std::move(context), std::move(options),
      [this](grpc::ClientContext* context, grpc::CompletionQueue* cq) {
        return $grpc_stub$->PrepareAsync$method_name$(context, cq);
      });
}
`)
			continue
		}
		if isLongrunning(m) {
			p.PrintWith(mVars, `
future<StatusOr<google::longrunning::Operation>>
Default$stub_class_name$::Async$method_name$(
      google::cloud::CompletionQueue& cq,
      std::shared_ptr<grpc::ClientContext> context,
      google::cloud::internal::ImmutableOptions,
      $request_type$ const& request) {
  return internal::MakeUnaryRpcImpl<$request_type$,
                                    google::longrunning::Operation>(
      cq,
      [this](grpc::ClientContext* context,
             $request_type$ const& request,
             grpc::CompletionQueue* cq) {
        return $grpc_stub$->Async$method_name$(context, request, cq);
      },
      request, std::move(context));
}

StatusOr<google::longrunning::Operation>
Default$stub_class_name$::$method_name$(
      grpc::ClientContext& context,
      Options,
      $request_type$ const& request) {
    google::longrunning::Operation response;
    auto status =
        $grpc_stub$->$method_name$(&context, request, &response);
    if (!status.ok()) {
      return google::cloud::MakeStatusFromRpcError(status);
    }
    return response;
}
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::StreamingReadRpc<$response_type$>>
Default$stub_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const&,
    $request_type$ const& request) {
  auto stream = $grpc_stub$->$method_name$(context.get(), request);
  return std::make_unique<google::cloud::internal::StreamingReadRpcImpl<
      $response_type$>>(
      std::move(context), std::move(stream));
}
`)
			continue
		}
		if isResponseTypeEmpty(m) {
			p.PrintWith(mVars, `
Status
Default$stub_class_name$::$method_name$(
  grpc::ClientContext& context, Options const&,
  $request_type$ const& request) {
    $response_type$ response;
    auto status =
        $grpc_stub$->$method_name$(&context, request, &response);
    if (!status.ok()) {
      return google::cloud::MakeStatusFromRpcError(status);
    }
    return google::cloud::Status();
}
`)
			continue
		}
		p.PrintWith(mVars, `
StatusOr<$response_type$>
Default$stub_class_name$::$method_name$(
  grpc::ClientContext& context, Options const&,
  $request_type$ const& request) {
    $response_type$ response;
    auto status =
        $grpc_stub$->$method_name$(&context, request, &response);
    if (!status.ok()) {
      return google::cloud::MakeStatusFromRpcError(status);
    }
    return response;
}
`)
	}

	for _, m := range asyncMethods {
		if isBidiStreaming(m) || isLongrunning(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::internal::AsyncStreamingReadRpc<
    $response_type$>>
Default$stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  return google::cloud::internal::MakeStreamingReadRpc<$request_type$, $response_type$>(
    cq, std::move(context), std::move(options), request,
    [this](grpc::ClientContext* context, $request_type$ const& request, grpc::CompletionQueue* cq) {
      return $grpc_stub$->PrepareAsync$method_name$(context, request, cq);
    });
}
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::internal::AsyncStreamingWriteRpc<
    $request_type$, $response_type$>>
Default$stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  return google::cloud::internal::MakeStreamingWriteRpc<$request_type$, $response_type$>(
    cq, std::move(context), std::move(options),
    [this](grpc::ClientContext* context, $response_type$* response, grpc::CompletionQueue* cq) {
      return $grpc_stub$->PrepareAsync$method_name$(context, response, cq);
    });
}
`)
			continue
		}
		if isResponseTypeEmpty(m) {
			p.PrintWith(mVars, `
future<Status>
Default$stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    // NOLINTNEXTLINE(performance-unnecessary-value-param)
    google::cloud::internal::ImmutableOptions,
    $request_type$ const& request) {
  return internal::MakeUnaryRpcImpl<$request_type$,
                                    $response_type$>(
      cq,
      [this](grpc::ClientContext* context,
             $request_type$ const& request,
             grpc::CompletionQueue* cq) {
        return $grpc_stub$->Async$method_name$(context, request, cq);
      },
      request, std::move(context))
          .then([](future<StatusOr<$response_type$>> f) {
            return f.get().status();
          });
}
`)
			continue
		}
		p.PrintWith(mVars, `
future<StatusOr<$response_type$>>
Default$stub_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    // NOLINTNEXTLINE(performance-unnecessary-value-param)
    google::cloud::internal::ImmutableOptions,
    $request_type$ const& request) {
  return internal::MakeUnaryRpcImpl<$request_type$,
                                    $response_type$>(
      cq,
      [this](grpc::ClientContext* context,
             $request_type$ const& request,
             grpc::CompletionQueue* cq) {
        return $grpc_stub$->Async$method_name$(context, request, cq);
      },
      request, std::move(context));
}
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
Default$stub_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    // NOLINTNEXTLINE(performance-unnecessary-value-param)
    google::cloud::internal::ImmutableOptions,
    google::longrunning::GetOperationRequest const& request) {
  return internal::MakeUnaryRpcImpl<google::longrunning::GetOperationRequest,
                                    google::longrunning::Operation>(
      cq,
      [this](grpc::ClientContext* context,
             google::longrunning::GetOperationRequest const& request,
             grpc::CompletionQueue* cq) {
        return operations_stub_->AsyncGetOperation(context, request, cq);
      },
      request, std::move(context));
}

future<Status> Default$stub_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    // NOLINTNEXTLINE(performance-unnecessary-value-param)
    google::cloud::internal::ImmutableOptions,
    google::longrunning::CancelOperationRequest const& request) {
  return internal::MakeUnaryRpcImpl<google::longrunning::CancelOperationRequest,
                                    google::protobuf::Empty>(
      cq,
      [this](grpc::ClientContext* context,
             google::longrunning::CancelOperationRequest const& request,
             grpc::CompletionQueue* cq) {
        return operations_stub_->AsyncCancelOperation(context, request, cq);
      },
      request, std::move(context))
      .then([](future<StatusOr<google::protobuf::Empty>> f) {
        return f.get().status();
      });
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
