// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateRoundRobinDecoratorHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["round_robin_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_header_path"],
		"google/cloud/version.h",
	})
	p.SystemIncludes([]string{"memory", "mutex", "vector"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
class $round_robin_class_name$ : public $stub_class_name$ {
 public:
  explicit $round_robin_class_name$(
      std::vector<std::shared_ptr<$stub_class_name$>> children);
  ~$round_robin_class_name$() override = default;
`)

	printDecoratorPublicMethods(p, svc, methods, asyncMethods, vars, lib, model)

	p.Print(`
 private:
  std::shared_ptr<$stub_class_name$> Child();

  std::vector<std::shared_ptr<$stub_class_name$>> const children_;
  std::mutex mu_;
  std::size_t current_ = 0;
};
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateRoundRobinDecoratorCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["round_robin_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{vars["round_robin_header_path"]})
	p.SystemIncludes([]string{"memory", "mutex", "vector"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
$round_robin_class_name$::$round_robin_class_name$(
    std::vector<std::shared_ptr<$stub_class_name$>> children)
    : children_(std::move(children)) {}
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::StreamingReadRpc<$response_type$>>
$round_robin_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const& options,
    $request_type$ const& request) {
  return Child()->$method_name$(std::move(context), options, request);
}
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::StreamingWriteRpc<
    $request_type$, $response_type$>>
$round_robin_class_name$::$method_name$(
    std::shared_ptr<grpc::ClientContext> context,
    Options const& options) {
  return Child()->$method_name$(std::move(context), options);
}
`)
			continue
		}
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$round_robin_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  return Child()->Async$method_name$(
      cq, std::move(context), std::move(options));
}
`)
			continue
		}
		if isLongrunning(m) {
			p.PrintWith(mVars, `
future<StatusOr<google::longrunning::Operation>>
$round_robin_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  return Child()->Async$method_name$(
      cq, std::move(context), std::move(options), request);
}

StatusOr<google::longrunning::Operation>
$round_robin_class_name$::$method_name$(
      grpc::ClientContext& context,
      Options options,
      $request_type$ const& request) {
  return Child()->$method_name$(context, options, request);
}
`)
			continue
		}
		p.PrintWith(mVars, `
$return_type$ $round_robin_class_name$::$method_name$(
    grpc::ClientContext& context,
    Options const& options,
    $request_type$ const& request) {
  return Child()->$method_name$(context, options, request);
}
`)
	}

	for _, m := range asyncMethods {
		if isBidiStreaming(m) || isLongrunning(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::AsyncStreamingReadRpc<
    $response_type$>>
$round_robin_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  return Child()->Async$method_name$(
      cq, std::move(context), std::move(options), request);
}
`)
			continue
		}
		if isStreamingWrite(m) {
			p.PrintWith(mVars, `
std::unique_ptr<google::cloud::internal::AsyncStreamingWriteRpc<
    $request_type$,
    $response_type$>>
$round_robin_class_name$::Async$method_name$(
    google::cloud::CompletionQueue const& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options) {
  return Child()->Async$method_name$(
      cq, std::move(context), std::move(options));
}
`)
			continue
		}
		p.PrintWith(mVars, `
future<$return_type$>
$round_robin_class_name$::Async$method_name$(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    $request_type$ const& request) {
  return Child()->Async$method_name$(
      cq, std::move(context), std::move(options), request);
}
`)
	}

	if hasLongrunningMethod(methods) {
		p.Print(`
future<StatusOr<google::longrunning::Operation>>
$round_robin_class_name$::AsyncGetOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::GetOperationRequest const& request) {
  return Child()->AsyncGetOperation(
      cq, std::move(context), std::move(options), request);
}

future<Status>
$round_robin_class_name$::AsyncCancelOperation(
    google::cloud::CompletionQueue& cq,
    std::shared_ptr<grpc::ClientContext> context,
    google::cloud::internal::ImmutableOptions options,
    google::longrunning::CancelOperationRequest const& request) {
  return Child()->AsyncCancelOperation(
      cq, std::move(context), std::move(options), request);
}
`)
	}

	p.Print(`
std::shared_ptr<$stub_class_name$>
$round_robin_class_name$::Child() {
  std::unique_lock<std::mutex> lk(mu_);
  auto const current = current_;
  if (++current_ == children_.size()) current_ = 0;
  lk.unlock();
  return children_[current];
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
