// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateMockConnectionHeader(svc *api.Service, serviceVars map[string]string, methods []*api.Method, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["mock_connection_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{vars["connection_header_path"]})
	p.SystemIncludes([]string{"gmock/gmock.h"})

	p.HeaderOpenNamespaces(vars["product_mocks_namespace"])

	p.Print(`
/**
 * A class to mock ` + "`$connection_class_name$`" + `.
 *
 * Application developers may want to test their code with simulated responses,
 * including errors, from an object of type ` + "`$client_class_name$`" + `. To do so,
 * construct an object of type ` + "`$client_class_name$`" + ` with an instance of this
 * class. Then use the Google Test framework functions to program the behavior
 * of this mock.
 *
 * @see [This example][bq-mock] for how to test your application with GoogleTest.
 * While the example showcases types from the BigQuery library, the underlying
 * principles apply for any pair of ` + "`*Client` and `*Connection`" + `.
 *
 * [bq-mock]: @cloud_cpp_docs_link{bigquery,bigquery-read-mock}
 */
class $mock_connection_class_name$ : public $product_namespace$::$connection_class_name$ {
 public:
  MOCK_METHOD(Options, options, (), (override));
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
  MOCK_METHOD((std::unique_ptr<
      ::google::cloud::AsyncStreamingReadWriteRpc<
          $request_type$, $response_type$>>),
      Async$method_name$, (), (override));
`)
			continue
		}
		if isNonStreaming(m) && !isLongrunning(m) && !isPaginated(m) {
			p.PrintWith(mVars, `
  MOCK_METHOD($return_type$,
  $method_name$,
  ($request_type$ const& request), (override));
`)
			continue
		}
		if isNonStreaming(m) && isLongrunning(m) && !isPaginated(m) {
			p.PrintWith(mVars, `
  /// To disambiguate calls, use:
  ///
  /// @code
  /// using ::testing::_;
  /// using ::testing::Matcher;
  /// EXPECT_CALL(*mock, $method_name$(Matcher<$request_type$ const&>(_)))
  /// @endcode
  MOCK_METHOD(future<StatusOr<$longrunning_deduced_response_type$>>,
  $method_name$,
  ($request_type$ const& request), (override));


  /// To disambiguate calls, use:
  ///
  /// @code
  /// using ::testing::_;
  /// EXPECT_CALL(*mock, $method_name$(_, _))
  /// @endcode
  MOCK_METHOD(StatusOr<$longrunning_operation_type$>,
  $method_name$, (NoAwaitTag,
    $request_type$ const& request), (override));


  /// To disambiguate calls, use:
  ///
  /// @code
  /// using ::testing::_;
  /// using ::testing::Matcher;
  /// EXPECT_CALL(*mock, $method_name$(Matcher<$longrunning_operation_type$ const&>(_)))
  /// @endcode
  MOCK_METHOD(future<StatusOr<$longrunning_deduced_response_type$>>,
  $method_name$, (
    $longrunning_operation_type$ const& operation), (override));
`)
			continue
		}
		if isNonStreaming(m) && !isLongrunning(m) && isPaginated(m) {
			p.PrintWith(mVars, `
  MOCK_METHOD((StreamRange<$range_output_type$>),
  $method_name$,
  ($request_type$ request), (override));
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  MOCK_METHOD(StreamRange<$response_type$>,
  $method_name$,
  ($request_type$ const& request), (override));
`)
			continue
		}
	}

	for _, m := range asyncMethods {
		if isNonStreaming(m) && !isLongrunning(m) && !isPaginated(m) {
			mVars := buildMethodVars(svc, m, vars, lib, model)
			p.PrintWith(mVars, `
  MOCK_METHOD(future<$return_type$>,
  Async$method_name$,
  ($request_type$ const& request), (override));
`)
		}
	}

	p.Print(`};
`)

	p.HeaderCloseNamespaces(vars["product_mocks_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}
