// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateOptionDefaultsHeader(_ *api.Service, serviceVars map[string]string, _ *config.Library) (string, string) {
	headerPath := serviceVars["option_defaults_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		"google/cloud/options.h",
		"google/cloud/version.h",
	})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
Options $service_name$DefaultOptions(Options options);
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateOptionDefaultsCc(_ *api.Service, serviceVars map[string]string, methods []*api.Method, _ *config.Library) (string, string) {
	ccPath := serviceVars["option_defaults_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{
		vars["option_defaults_header_path"],
		vars["connection_header_path"],
		vars["options_header_path"],
		"google/cloud/internal/populate_common_options.h",
		"google/cloud/internal/populate_grpc_options.h",
	})
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
namespace {
auto constexpr kBackoffScaling = 2.0;
}  // namespace

Options $service_name$DefaultOptions(Options options) {
  options = internal::PopulateCommonOptions(
      std::move(options), "$service_endpoint_env_var$",
      "$emulator_endpoint_env_var$", "$service_authority_env_var$",
      "$service_endpoint$");
  options = internal::PopulateGrpcOptions(std::move(options));
  if (!options.has<$product_namespace$::$retry_policy_name$Option>()) {
    options.set<$product_namespace$::$retry_policy_name$Option>(
        $product_namespace$::$limited_time_retry_policy_name$(
            std::chrono::minutes(30)).clone());
  }
  if (!options.has<$product_namespace$::$service_name$BackoffPolicyOption>()) {
    options.set<$product_namespace$::$service_name$BackoffPolicyOption>(
        ExponentialBackoffPolicy(std::chrono::seconds(0), std::chrono::seconds(1),
            std::chrono::minutes(5), kBackoffScaling, kBackoffScaling).clone());
  }
`)

	if hasLongrunningMethod(methods) {
		p.Print(`  if (!options.has<$product_namespace$::$service_name$PollingPolicyOption>()) {
    options.set<$product_namespace$::$service_name$PollingPolicyOption>(
        GenericPollingPolicy<
            $product_namespace$::$retry_policy_name$Option::Type,
            $product_namespace$::$service_name$BackoffPolicyOption::Type>(
            options.get<$product_namespace$::$retry_policy_name$Option>()->clone(),
            ExponentialBackoffPolicy(std::chrono::seconds(1),
            std::chrono::minutes(5), kBackoffScaling).clone()).clone());
  }
`)
	}

	p.Print(`  if (!options.has<$product_namespace$::$idempotency_class_name$Option>()) {
    options.set<$product_namespace$::$idempotency_class_name$Option>(
        $product_namespace$::MakeDefault$idempotency_class_name$());
  }

  return options;
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
