// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
)

func generateRestConnectionHeader(serviceVars map[string]string, lib *config.Library) (string, string) {
	headerPath := serviceVars["connection_rest_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["connection_header_path"],
		"google/cloud/options.h",
		"google/cloud/version.h",
	})

	locationStyle := ""
	if lib != nil && lib.Cpp != nil {
		locationStyle = lib.Cpp.EndpointLocationStyle
	}
	isLocationDependent := locationStyle == "LOCATION_DEPENDENT" ||
		locationStyle == "LOCATION_DEPENDENT_COMPAT" ||
		locationStyle == "LOCATION_OPTIONALLY_DEPENDENT"

	sysIncludes := []string{"memory"}
	if isLocationDependent {
		sysIncludes = append(sysIncludes, "string")
	}
	p.SystemIncludes(sysIncludes)

	p.HeaderOpenNamespaces(vars["product_namespace"])

	locationDoc := ""
	if isLocationDependent {
		locationDoc = "\n * @param location Sets the prefix for the default `EndpointOption` value."
	}

	p.Print(`
/**
 * A factory function to construct an object of type ` + "`$connection_class_name$`" + `
 * that uses REST over HTTP as transport in lieu of gRPC. REST transport should
 * only be used for services that do not support gRPC or if the existing network
 * configuration precludes using gRPC.
 *
 * The returned connection object should not be used directly; instead it
 * should be passed as an argument to the constructor of $client_class_name$.
 *
 * The optional @p options argument may be used to configure aspects of the
 * returned ` + "`$connection_class_name$`" + `. Expected options are any of the types in
 * the following option lists:
 *
 * - ` + "`google::cloud::CommonOptionList`" + `
 * - ` + "`google::cloud::RestOptionList`" + `
 * - ` + "`google::cloud::UnifiedCredentialsOptionList`" + `
 * - ` + "`google::cloud::$product_namespace$::$service_name$PolicyOptionList`" + `
 *
 * @note Unexpected options will be ignored. To log unexpected options instead,
 *     set ` + "`GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes`" + ` in the environment.
 *` + locationDoc + `
 * @param options (optional) Configure the ` + "`$connection_class_name$`" + ` created by
 * this function.
 */
std::shared_ptr<$connection_class_name$> Make$connection_class_name$Rest(
`)

	if isLocationDependent {
		p.Print(`    std::string const& location, Options options = {});
`)
		switch locationStyle {
		case "LOCATION_DEPENDENT_COMPAT":
			p.Print(`
/**
 * A backwards-compatible version of the previous factory function.  Unless
 * the service also offers a global endpoint, the default value of the
 * ` + "`EndpointOption`" + ` may be useless, in which case it must be overridden.
 *
 * @deprecated Please use the ` + "`location`" + ` overload instead.
 */
std::shared_ptr<$connection_class_name$> Make$connection_class_name$Rest(
    Options options = {});
`)
		case "LOCATION_OPTIONALLY_DEPENDENT":
			p.Print(`
/**
 * A factory function to construct an object of type ` + "`$connection_class_name$`" + `.
 *
 * This overload of ` + "`Make$connection_class_name$Rest`" + ` does not require a location
 * argument, creating a connection to the global service endpoint.
 */
std::shared_ptr<$connection_class_name$> Make$connection_class_name$Rest(
    Options options = {});
`)
		}
	} else {
		p.Print(`    Options options = {});
`)
	}

	p.HeaderCloseNamespaces(vars["product_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateRestConnectionCc(serviceVars map[string]string, lib *config.Library) (string, string) {
	ccPath := serviceVars["connection_rest_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{
		vars["connection_rest_header_path"],
		vars["options_header_path"],
		vars["option_defaults_header_path"],
		vars["connection_impl_rest_header_path"],
		vars["stub_factory_rest_header_path"],
		vars["tracing_connection_header_path"],
		"google/cloud/common_options.h",
		"google/cloud/credentials.h",
		"google/cloud/internal/rest_background_threads_impl.h",
		"google/cloud/internal/rest_options.h",
	})
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_namespace"])

	locationStyle := ""
	if lib != nil && lib.Cpp != nil {
		locationStyle = lib.Cpp.EndpointLocationStyle
	}
	isLocationDependent := locationStyle == "LOCATION_DEPENDENT" ||
		locationStyle == "LOCATION_DEPENDENT_COMPAT" ||
		locationStyle == "LOCATION_OPTIONALLY_DEPENDENT"

	if isLocationDependent {
		p.Print(`
std::shared_ptr<$connection_class_name$> Make$connection_class_name$Rest(
    std::string const& location, Options options) {
  internal::CheckExpectedOptions<CommonOptionList, RestOptionList,
      UnifiedCredentialsOptionList, rest_internal::TargetApiVersionOption,
      $service_name$PolicyOptionList>(options, __func__);
  options = $product_internal_namespace$::$service_name$DefaultOptions(
      location, std::move(options));
  auto background = std::make_unique<
      rest_internal::AutomaticallyCreatedRestBackgroundThreads>();
  auto stub = $product_internal_namespace$::CreateDefault$stub_rest_class_name$(
      options);
  return $product_internal_namespace$::Make$tracing_connection_class_name$(
      std::make_shared<
          $product_internal_namespace$::$connection_impl_rest_class_name$>(
          std::move(background), std::move(stub), std::move(options)));
}
`)
		if locationStyle == "LOCATION_OPTIONALLY_DEPENDENT" || locationStyle == "LOCATION_DEPENDENT_COMPAT" {
			p.Print(`
std::shared_ptr<$connection_class_name$> Make$connection_class_name$Rest(
    Options options) {
  return Make$connection_class_name$Rest(std::string{}, std::move(options));
}
`)
		}
	} else {
		p.Print(`
std::shared_ptr<$connection_class_name$> Make$connection_class_name$Rest(
    Options options) {
  internal::CheckExpectedOptions<CommonOptionList, RestOptionList,
      UnifiedCredentialsOptionList, rest_internal::TargetApiVersionOption,
      $service_name$PolicyOptionList>(options, __func__);
  options = $product_internal_namespace$::$service_name$DefaultOptions(
      std::move(options));
  auto background = std::make_unique<
      rest_internal::AutomaticallyCreatedRestBackgroundThreads>();
  auto stub = $product_internal_namespace$::CreateDefault$stub_rest_class_name$(
      options);
  return $product_internal_namespace$::Make$tracing_connection_class_name$(
      std::make_shared<
          $product_internal_namespace$::$connection_impl_rest_class_name$>(
          std::move(background), std::move(stub), std::move(options)));
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_namespace"])

	return filepath.Clean(ccPath), p.String()
}
