// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func generateTracingConnectionHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["tracing_connection_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["connection_header_path"],
		"google/cloud/version.h",
	})
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

class $tracing_connection_class_name$
    : public $product_namespace$::$connection_class_name$ {
 public:
  ~$tracing_connection_class_name$() override = default;

  explicit $tracing_connection_class_name$(
    std::shared_ptr<$product_namespace$::$connection_class_name$> child);

  Options options() override { return child_->options(); }
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
  std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
      $request_type$,
      $response_type$>>
  Async$method_name$() override;
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
  StreamRange<$response_type$>
  $method_name$($request_type$ const& request) override;
`)
			continue
		}
		if isStreamingWrite(m) {
			continue
		}
		if isPaginated(m) {
			p.PrintWith(mVars, `
  StreamRange<$range_output_type$>
  $method_name$($request_type$ request) override;
`)
			continue
		}
		if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
  future<Status>
  $method_name$($request_type$ const& request) override;

  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag,
      $request_type$ const& request) override;

  future<Status>
  $method_name$(
      $longrunning_operation_type$ const& operation) override;
`)
			} else {
				p.PrintWith(mVars, `
  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($request_type$ const& request) override;

  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag,
      $request_type$ const& request) override;

  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$(
      $longrunning_operation_type$ const& operation) override;
`)
			}
			continue
		}
		p.PrintWith(mVars, `
  $return_type$
  $method_name$($request_type$ const& request) override;
`)
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
  future<$return_type$>
  Async$method_name$($request_type$ const& request) override;
`)
	}

	p.Print(`
 private:
  std::shared_ptr<$product_namespace$::$connection_class_name$> child_;
};

#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

/**
 * Conditionally applies the tracing decorator to the given connection.
 *
 * The connection is only decorated if tracing is enabled (as determined by the
 * connection's options).
 */
std::shared_ptr<$product_namespace$::$connection_class_name$>
Make$tracing_connection_class_name$(
    std::shared_ptr<$product_namespace$::$connection_class_name$> conn);
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	relPath := filepath.Clean(headerPath)
	return relPath, p.String()
}

func generateTracingConnectionCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["tracing_connection_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	localIncludes := []string{
		vars["tracing_connection_header_path"],
		"google/cloud/internal/opentelemetry.h",
	}
	if hasPaginatedMethod(methods) || hasStreamingReadMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/internal/traced_stream_range.h")
	}
	p.CcLocalIncludes(localIncludes)

	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

$tracing_connection_class_name$::$tracing_connection_class_name$(
    std::shared_ptr<$product_namespace$::$connection_class_name$> child)
    : child_(std::move(child)) {}
`)

	for _, m := range methods {
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$tracing_connection_class_name$::Async$method_name$() {
  return child_->Async$method_name$();
}
`)
			continue
		}
		if isStreamingRead(m) {
			p.PrintWith(mVars, `
StreamRange<$response_type$>
$tracing_connection_class_name$::$method_name$($request_type$ const& request) {
  auto span = internal::MakeSpan("$product_namespace$::$connection_class_name$::$method_name$");
  internal::OTelScope scope(span);
  auto sr = child_->$method_name$(request);
  return internal::MakeTracedStreamRange<$response_type$>(
        std::move(span), std::move(sr));
}
`)
			continue
		}
		if isStreamingWrite(m) {
			continue
		}
		if isPaginated(m) {
			p.PrintWith(mVars, `
StreamRange<$range_output_type$>
$tracing_connection_class_name$::$method_name$($request_type$ request) {
  auto span = internal::MakeSpan("$product_namespace$::$connection_class_name$::$method_name$");
  internal::OTelScope scope(span);
  auto sr = child_->$method_name$(std::move(request));
  return internal::MakeTracedStreamRange<$range_output_type$>(
        std::move(span), std::move(sr));
}
`)
			continue
		}
		if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				mVars["lro_return_type"] = "future<Status>"
			} else {
				mVars["lro_return_type"] = "future<StatusOr<" + mVars["longrunning_deduced_response_type"] + ">>"
			}
			p.PrintWith(mVars, `
$lro_return_type$
$tracing_connection_class_name$::$method_name$($request_type$ const& request) {
  auto span = internal::MakeSpan(
      "$product_namespace$::$connection_class_name$::$method_name$");
  internal::OTelScope scope(span);
  return internal::EndSpan(std::move(span), child_->$method_name$(request));
}

StatusOr<$longrunning_operation_type$>
$tracing_connection_class_name$::$method_name$(
    NoAwaitTag, $request_type$ const& request) {
  auto span = internal::MakeSpan(
      "$product_namespace$::$connection_class_name$::$method_name$");
  opentelemetry::trace::Scope scope(span);
  return internal::EndSpan(*span, child_->$method_name$(
      NoAwaitTag{}, request));
}

$lro_return_type$
$tracing_connection_class_name$::$method_name$(
    $longrunning_operation_type$ const& operation) {
  auto span = internal::MakeSpan(
      "$product_namespace$::$connection_class_name$::$method_name$");
  internal::OTelScope scope(span);
  return internal::EndSpan(std::move(span),
      child_->$method_name$(operation));
}
`)
			continue
		}
		p.PrintWith(mVars, `
$return_type$
$tracing_connection_class_name$::$method_name$($request_type$ const& request) {
  auto span = internal::MakeSpan("$product_namespace$::$connection_class_name$::$method_name$");
  auto scope = opentelemetry::trace::Scope(span);
  return internal::EndSpan(*span, child_->$method_name$(request));
}
`)
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		p.PrintWith(mVars, `
future<$return_type$>
$tracing_connection_class_name$::Async$method_name$($request_type$ const& request) {
  auto span = internal::MakeSpan(
      "$product_namespace$::$connection_class_name$::Async$method_name$");
  internal::OTelScope scope(span);
  return internal::EndSpan(std::move(span), child_->Async$method_name$(request));
}
`)
	}

	p.Print(`
#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY

std::shared_ptr<$product_namespace$::$connection_class_name$>
Make$tracing_connection_class_name$(
    std::shared_ptr<$product_namespace$::$connection_class_name$> conn) {
#ifdef GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  if (internal::TracingEnabled(conn->options())) {
    conn = std::make_shared<$tracing_connection_class_name$>(std::move(conn));
  }
#endif  // GOOGLE_CLOUD_CPP_HAVE_OPENTELEMETRY
  return conn;
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	relPath := filepath.Clean(ccPath)
	return relPath, p.String()
}
