// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"slices"

	"github.com/googleapis/librarian/internal/config"
)

// generateSourcesCc generates the internal/<service>_sources.cc unity build file.
func generateSourcesCc(serviceVars map[string]string, hasGrpc, hasRest bool, lib *config.Library) (string, string) {
	outPath := serviceVars["sources_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	// This generator was added in 2024. We do not want to create new files with a copyright date in the past.
	vars["copyright_year"] = max("2024", vars["copyright_year"])

	var sources []string
	sources = append(sources,
		vars["client_cc_path"],
		vars["connection_cc_path"],
		vars["idempotency_policy_cc_path"],
		vars["option_defaults_cc_path"],
		vars["tracing_connection_cc_path"],
	)

	if hasGrpc {
		sources = append(sources,
			vars["connection_impl_cc_path"],
			vars["stub_factory_cc_path"],
			vars["auth_cc_path"],
			vars["logging_cc_path"],
			vars["metadata_cc_path"],
			vars["stub_cc_path"],
			vars["tracing_stub_cc_path"],
		)
		if lib != nil && lib.Cpp != nil && lib.Cpp.GenerateRoundRobinDecorator {
			sources = append(sources, vars["round_robin_cc_path"])
		}
	}

	if hasRest {
		sources = append(sources,
			vars["connection_rest_cc_path"],
			vars["connection_impl_rest_cc_path"],
			vars["logging_rest_cc_path"],
			vars["metadata_rest_cc_path"],
			vars["stub_factory_rest_cc_path"],
			vars["stub_rest_cc_path"],
		)
	}

	slices.Sort(sources)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

// NOLINTBEGIN(bugprone-suspicious-include)
`)
	p.HeaderLocalIncludes(sources)
	p.Print(`// NOLINTEND(bugprone-suspicious-include)
`)

	return outPath, p.String()
}
