// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"maps"
	"path/filepath"
)

func generateRestStubFactoryHeader(serviceVars map[string]string) (string, string) {
	headerPath := serviceVars["stub_factory_rest_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	p.HeaderLocalIncludes([]string{
		vars["stub_rest_header_path"],
		"google/cloud/options.h",
		"google/cloud/version.h",
	})
	p.SystemIncludes([]string{"memory"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
std::shared_ptr<$stub_rest_class_name$> CreateDefault$stub_rest_class_name$(
    Options const& options);
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateRestStubFactoryCc(serviceVars map[string]string) (string, string) {
	ccPath := serviceVars["stub_factory_rest_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	p.CcLocalIncludes([]string{
		vars["stub_factory_rest_header_path"],
		"absl/strings/match.h",
		vars["logging_rest_header_path"],
		vars["metadata_rest_header_path"],
		vars["stub_rest_header_path"],
		"google/cloud/common_options.h",
		"google/cloud/internal/algorithm.h",
		"google/cloud/internal/populate_rest_options.h",
		"google/cloud/log.h",
		"google/cloud/options.h",
		"google/cloud/rest_options.h",
	})
	p.SystemIncludes([]string{"memory", "utility"})

	p.HeaderOpenNamespaces(vars["product_internal_namespace"])

	p.Print(`
std::shared_ptr<$stub_rest_class_name$>
CreateDefault$stub_rest_class_name$(Options const& options) {
  auto opts = internal::PopulateRestOptions(options);
  std::shared_ptr<$stub_rest_class_name$> stub =
      std::make_shared<Default$stub_rest_class_name$>(std::move(opts));
  stub = std::make_shared<$metadata_rest_class_name$>(std::move(stub));
  if (internal::Contains(
      options.get<LoggingComponentsOption>(), "rpc")) {
    GCP_LOG(INFO) << "Enabled logging for REST rpc calls";
    stub = std::make_shared<$logging_rest_class_name$>(
        std::move(stub),
        options.get<RestTracingOptionsOption>(),
        options.get<LoggingComponentsOption>());
  }
  return stub;
}
`)

	p.HeaderCloseNamespaces(vars["product_internal_namespace"])

	return filepath.Clean(ccPath), p.String()
}
