// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"fmt"
	"maps"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

type signatureInfo struct {
	index int
	sig   *api.MethodSignature
}

func getValidSignatures(svc *api.Service, m *api.Method, lib *config.Library) []signatureInfo {
	omitted := make(map[string]bool)
	if lib != nil && lib.Cpp != nil {
		for _, o := range lib.Cpp.OmittedRPCs {
			omitted[o] = true
		}
	}

	var res []signatureInfo
	seenUIDs := make(map[string]bool)
	validIndex := 0
	for _, sig := range m.Signatures {
		var uidPieces []string
		for _, f := range sig.Fields {
			var cppType string
			if f.Map {
				keyType := "std::string"
				valType := "std::string"
				if f.MessageType != nil && len(f.MessageType.Fields) >= 2 {
					keyType = cppTypeToString(f.MessageType.Fields[0])
					valType = cppTypeToString(f.MessageType.Fields[1])
				}
				cppType = fmt.Sprintf("std::map<%s, %s> const&", keyType, valType)
			} else if f.Repeated {
				elemType := cppTypeToString(f)
				cppType = fmt.Sprintf("std::vector<%s> const&", elemType)
			} else if f.Typez == api.TypezMessage || f.Typez == api.TypezString || f.Typez == api.TypezBytes {
				cppType = cppTypeToString(f) + " const&"
			} else {
				cppType = cppTypeToString(f)
			}
			uidPieces = append(uidPieces, cppType)
		}
		uid := strings.Join(uidPieces, ", ") + ", "
		if seenUIDs[uid] {
			continue
		}
		seenUIDs[uid] = true

		sigName := fmt.Sprintf("%s(%s)", m.Name, strings.Join(uidPieces, ", "))
		qualifiedSigName := fmt.Sprintf("%s.%s", svc.Name, sigName)
		if omitted[sigName] || omitted[qualifiedSigName] {
			continue
		}

		res = append(res, signatureInfo{
			index: validIndex,
			sig:   sig,
		})
		validIndex++
	}
	return res
}

func methodSignatureUsesDeprecatedField(svc *api.Service, methods []*api.Method, lib *config.Library) bool {
	for _, m := range methods {
		sigs := getValidSignatures(svc, m, lib)
		for _, s := range sigs {
			for _, f := range s.sig.Fields {
				if f.Deprecated {
					return true
				}
			}
		}
	}
	return false
}

func generateClientHeader(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	headerPath := serviceVars["client_header_path"]
	guard := formatHeaderIncludeGuard(headerPath)
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)
	vars["header_include_guard"] = guard

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

#ifndef $header_include_guard$
#define $header_include_guard$

`)

	hasIAM, setMethod := hasIamPolicyExtension(methods)

	hasGrpc := lib == nil || lib.Cpp == nil || lib.Cpp.HasGrpcTransport()
	connectionHeader := vars["connection_header_path"]
	if !hasGrpc {
		connectionHeader = vars["connection_rest_header_path"]
	}

	var localIncludes []string
	localIncludes = append(localIncludes,
		connectionHeader,
		"google/cloud/future.h",
		"google/cloud/options.h",
		"google/cloud/polling_policy.h",
		"google/cloud/status_or.h",
		"google/cloud/version.h",
	)
	if hasLongrunningMethod(methods) {
		localIncludes = append(localIncludes, "google/cloud/no_await_tag.h")
	}
	if hasIAM {
		localIncludes = append(localIncludes, "google/cloud/internal/make_status.h")
	}
	p.HeaderLocalIncludes(localIncludes)
	if hasIAM {
		p.HeaderLocalIncludes([]string{"google/cloud/iam_updater.h"})
	}

	var protoIncludes []string
	protoIncludes = append(protoIncludes, methodSignatureWellKnownProtobufTypeIncludes(methods)...)
	if hasLongrunningMethod(methods) {
		protoIncludes = append(protoIncludes, "google/longrunning/operations.grpc.pb.h")
	}
	p.ProtobufIncludes(protoIncludes)

	var sysIncludes []string
	if hasMessageWithMapField(methods, model) {
		sysIncludes = append(sysIncludes, "map")
	}
	sysIncludes = append(sysIncludes, "memory", "string")
	p.SystemIncludes(sysIncludes)

	p.HeaderOpenNamespaces(vars["product_namespace"])

	if svc.Deprecated {
		p.Print(`
$class_comment_block$
class
 GOOGLE_CLOUD_CPP_DEPRECATED(
      "$service_name$ has been deprecated and will be turned down in the future."
)
$client_class_name$ {`)
	} else {
		p.Print(`
$class_comment_block$
class $client_class_name$ {`)
	}

	p.Print(`
 public:
  explicit $client_class_name$(std::shared_ptr<$connection_class_name$> connection, Options opts = {});
  ~$client_class_name$();

  ///@{
  /// @name Copy and move support
  $client_class_name$($client_class_name$ const&) = default;
  $client_class_name$& operator=($client_class_name$ const&) = default;
  $client_class_name$($client_class_name$&&) = default;
  $client_class_name$& operator=($client_class_name$&&) = default;
  ///@}

  ///@{
  /// @name Equality
  friend bool operator==($client_class_name$ const& a, $client_class_name$ const& b) {
    return a.connection_ == b.connection_;
  }
  friend bool operator!=($client_class_name$ const& a, $client_class_name$ const& b) {
    return !(a == b);
  }
  ///@}
`)

	for _, m := range methods {
		if isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		isDep := m.Deprecated
		depMacro := ""
		if isDep {
			depMacro = "  GOOGLE_CLOUD_CPP_DEPRECATED(\"This RPC is deprecated.\")\n"
		}
		mVars["method_dep_macro"] = depMacro

		if isBidiStreaming(m) {
			comment := formatMethodComments(m, "", model)
			mVars["bidir_comment"] = comment
			p.PrintWith(mVars, `
$bidir_comment$$method_dep_macro$  std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
      $request_type$,
      $response_type$>>
  Async$method_name$(Options opts = {});
`)
			continue
		}

		sigs := getValidSignatures(svc, m, lib)
		for _, s := range sigs {
			idxStr := strconv.Itoa(s.index)
			sigComment := formatMethodCommentsMethodSignature(m, s.sig, model)
			mVars["sig_comment"] = sigComment
			mVars["current_method_signature"] = mVars["method_signature"+idxStr]

			if isLongrunning(m) {
				startComment := formatStartMethodComments(m.Name, mVars["longrunning_operation_type"], isDep)
				mVars["start_comment"] = startComment
				if isResponseTypeEmpty(m) {
					p.PrintWith(mVars, `
$sig_comment$$method_dep_macro$  future<Status>
  $method_name$($current_method_signature$Options opts = {});

$start_comment$$method_dep_macro$  Status
  $method_name$(NoAwaitTag, $current_method_signature$Options opts = {});
`)
				} else {
					p.PrintWith(mVars, `
$sig_comment$$method_dep_macro$  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($current_method_signature$Options opts = {});

$start_comment$$method_dep_macro$  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag, $current_method_signature$Options opts = {});
`)
				}
			} else if isPaginated(m) {
				p.PrintWith(mVars, `
$sig_comment$$method_dep_macro$  StreamRange<$range_output_type$>
  $method_name$($current_method_signature$Options opts = {});
`)
			} else if isStreamingRead(m) {
				p.PrintWith(mVars, `
$sig_comment$$method_dep_macro$  StreamRange<$response_type$>
  $method_name$($current_method_signature$Options opts = {});
`)
			} else {
				p.PrintWith(mVars, `
$sig_comment$$method_dep_macro$  $return_type$
  $method_name$($current_method_signature$Options opts = {});
`)
			}

			if hasIAM && setMethod == m {
				p.PrintWith(mVars, `
  /**
   * Updates the IAM policy for @p resource using an optimistic concurrency
   * control loop.
   *
   * The loop fetches the current policy for @p resource, and passes it to @p
   * updater, which should return the new policy. This new policy should use the
   * current etag so that the read-modify-write cycle can detect races and rerun
   * the update when there is a mismatch. If the new policy does not have an
   * etag, the existing policy will be blindly overwritten. If @p updater does
   * not yield a policy, the control loop is terminated and kCancelled is
   * returned.
   *
   * @param resource  Required. The resource for which the policy is being
   * specified. See the operation documentation for the appropriate value for
   * this field.
   * @param updater  Required. Functor to map the current policy to a new one.
   * @param opts  Optional. Override the class-level options, such as retry and
   *    backoff policies.
   * @return google::iam::v1::Policy
   */
  StatusOr<google::iam::v1::Policy>
  SetIamPolicy(std::string const& resource, IamUpdater const& updater, Options opts = {});
`)
			}
		}

		reqComment := formatMethodCommentsProtobufRequest(m, model)
		mVars["req_comment"] = reqComment

		if isLongrunning(m) {
			startComment := formatStartMethodComments(m.Name, mVars["longrunning_operation_type"], isDep)
			awaitComment := formatAwaitMethodComments(m.Name, mVars["longrunning_operation_type"], isDep)
			mVars["start_comment"] = startComment
			mVars["await_comment"] = awaitComment
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
$req_comment$$method_dep_macro$  future<Status>
  $method_name$($request_type$ const& request, Options opts = {});

$start_comment$$method_dep_macro$  Status
  $method_name$(NoAwaitTag, $request_type$ const& request, Options opts = {});

$await_comment$$method_dep_macro$  future<Status>
  $method_name$($longrunning_operation_type$ const& operation, Options opts = {});
`)
			} else {
				p.PrintWith(mVars, `
$req_comment$$method_dep_macro$  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($request_type$ const& request, Options opts = {});

$start_comment$$method_dep_macro$  StatusOr<$longrunning_operation_type$>
  $method_name$(NoAwaitTag, $request_type$ const& request, Options opts = {});

$await_comment$$method_dep_macro$  future<StatusOr<$longrunning_deduced_response_type$>>
  $method_name$($longrunning_operation_type$ const& operation, Options opts = {});
`)
			}
		} else if isPaginated(m) {
			p.PrintWith(mVars, `
$req_comment$$method_dep_macro$  StreamRange<$range_output_type$>
  $method_name$($request_type$ request, Options opts = {});
`)
		} else if isStreamingRead(m) {
			p.PrintWith(mVars, `
$req_comment$$method_dep_macro$  StreamRange<$response_type$>
  $method_name$($request_type$ const& request, Options opts = {});
`)
		} else {
			p.PrintWith(mVars, `
$req_comment$$method_dep_macro$  $return_type$
  $method_name$($request_type$ const& request, Options opts = {});
`)
		}
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		isDep := m.Deprecated
		depMacro := ""
		if isDep {
			depMacro = "  GOOGLE_CLOUD_CPP_DEPRECATED(\"This RPC is deprecated.\")\n"
		}
		mVars["method_dep_macro"] = depMacro

		sigs := getValidSignatures(svc, m, lib)
		for _, s := range sigs {
			idxStr := strconv.Itoa(s.index)
			sigComment := formatMethodCommentsMethodSignature(m, s.sig, model)
			mVars["sig_comment"] = sigComment
			mVars["current_method_signature"] = mVars["method_signature"+idxStr]
			p.PrintWith(mVars, `
$sig_comment$$method_dep_macro$  future<$return_type$>
  Async$method_name$($current_method_signature$Options opts = {});
`)
		}

		reqComment := formatMethodCommentsProtobufRequest(m, model)
		mVars["req_comment"] = reqComment
		p.PrintWith(mVars, `
$req_comment$$method_dep_macro$  future<$return_type$>
  Async$method_name$($request_type$ const& request, Options opts = {});
`)
	}

	p.Print(`
 private:
  std::shared_ptr<$connection_class_name$> connection_;
  Options options_;
};
`)

	p.HeaderCloseNamespaces(vars["product_namespace"])
	p.Print("\n#endif  // $header_include_guard$\n")

	return filepath.Clean(headerPath), p.String()
}

func generateClientCc(svc *api.Service, serviceVars map[string]string, methods, asyncMethods []*api.Method, lib *config.Library, model *api.API) (string, string) {
	ccPath := serviceVars["client_cc_path"]
	vars := make(map[string]string)
	maps.Copy(vars, serviceVars)

	p := newPrinter(vars)
	p.Print(p.CopyrightHeader(vars["copyright_year"]))
	p.Print(`
// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: $proto_file_name$

`)

	hasDepWarnings := methodSignatureUsesDeprecatedField(svc, methods, lib)
	hasIAM, setMethod := hasIamPolicyExtension(methods)

	if hasDepWarnings {
		p.Print("#include \"google/cloud/internal/disable_deprecation_warnings.inc\"\n")
	}
	p.Print(fmt.Sprintf("#include \"%s\"\n", vars["client_header_path"]))
	p.Print("#include <memory>\n")
	if hasIAM {
		p.Print(fmt.Sprintf("#include \"%s\"\n", vars["options_header_path"]))
		p.Print("#include <thread>\n")
	}
	p.Print("#include <utility>\n")

	p.HeaderOpenNamespaces(vars["product_namespace"])

	p.Print(`
$client_class_name$::$client_class_name$(
    std::shared_ptr<$connection_class_name$> connection, Options opts)
    : connection_(std::move(connection)),
      options_(internal::MergeOptions(std::move(opts),
      connection_->options())) {}
$client_class_name$::~$client_class_name$() = default;
`)

	for _, m := range methods {
		if isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		if isBidiStreaming(m) {
			p.PrintWith(mVars, `
std::unique_ptr<::google::cloud::AsyncStreamingReadWriteRpc<
    $request_type$,
    $response_type$>>
$client_class_name$::Async$method_name$(Options opts) {
  internal::OptionsSpan span(
      internal::MergeOptions(std::move(opts), options_));
  return connection_->Async$method_name$();
}
`)
			continue
		}

		sigs := getValidSignatures(svc, m, lib)
		for _, s := range sigs {
			idxStr := strconv.Itoa(s.index)
			mVars["current_method_signature"] = mVars["method_signature"+idxStr]
			mVars["current_request_setters"] = mVars["method_request_setters"+idxStr]

			if isLongrunning(m) {
				if isResponseTypeEmpty(m) {
					p.PrintWith(mVars, `
future<Status>
$client_class_name$::$method_name$($current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(request);
}

Status
$client_class_name$::$method_name$(NoAwaitTag, $current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(NoAwaitTag{}, request);
}
`)
				} else {
					p.PrintWith(mVars, `
future<StatusOr<$longrunning_deduced_response_type$>>
$client_class_name$::$method_name$($current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(request);
}

StatusOr<$longrunning_operation_type$>
$client_class_name$::$method_name$(NoAwaitTag, $current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(NoAwaitTag{}, request);
}
`)
				}
			} else if isPaginated(m) {
				p.PrintWith(mVars, `
StreamRange<$range_output_type$>
$client_class_name$::$method_name$($current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(request);
}
`)
			} else if isStreamingRead(m) {
				p.PrintWith(mVars, `
StreamRange<$response_type$>
$client_class_name$::$method_name$($current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(request);
}
`)
			} else {
				p.PrintWith(mVars, `
$return_type$
$client_class_name$::$method_name$($current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->$method_name$(request);
}
`)
			}

			if hasIAM && setMethod == m {
				p.PrintWith(mVars, `
StatusOr<google::iam::v1::Policy>
$client_class_name$::SetIamPolicy(std::string const& resource, IamUpdater const& updater, Options opts) {
  internal::CheckExpectedOptions<$service_name$BackoffPolicyOption>(opts, __func__);
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  google::iam::v1::GetIamPolicyRequest get_request;
  get_request.set_resource(resource);
  google::iam::v1::SetIamPolicyRequest set_request;
  set_request.set_resource(resource);
  auto backoff_policy = internal::CurrentOptions().get<$service_name$BackoffPolicyOption>();
  if (backoff_policy != nullptr) {
    backoff_policy = backoff_policy->clone();
  }
  for (;;) {
    auto recent = connection_->GetIamPolicy(get_request);
    if (!recent) {
      return recent.status();
    }
    auto policy = updater(*std::move(recent));
    if (!policy) {
      return internal::CancelledError(
          "updater did not yield a policy",
          GCP_ERROR_INFO().WithMetadata("gl-cpp.error.origin", "client"));
    }
    *set_request.mutable_policy() = *std::move(policy);
    auto result = connection_->SetIamPolicy(set_request);
    if (result ||
        result.status().code() != StatusCode::kAborted ||
        backoff_policy == nullptr) {
      return result;
    }
    std::this_thread::sleep_for(backoff_policy->OnCompletion());
  }
}
`)
			}
		}

		if isLongrunning(m) {
			if isResponseTypeEmpty(m) {
				p.PrintWith(mVars, `
future<Status>
$client_class_name$::$method_name$($request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(request);
}

Status
$client_class_name$::$method_name$(NoAwaitTag, $request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(NoAwaitTag{}, request);
}

future<Status>
$client_class_name$::$method_name$($longrunning_operation_type$ const& operation, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(operation);
}
`)
			} else {
				p.PrintWith(mVars, `
future<StatusOr<$longrunning_deduced_response_type$>>
$client_class_name$::$method_name$($request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(request);
}

StatusOr<$longrunning_operation_type$>
$client_class_name$::$method_name$(NoAwaitTag, $request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(NoAwaitTag{}, request);
}

future<StatusOr<$longrunning_deduced_response_type$>>
$client_class_name$::$method_name$($longrunning_operation_type$ const& operation, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(operation);
}
`)
			}
		} else if isPaginated(m) {
			p.PrintWith(mVars, `
StreamRange<$range_output_type$>
$client_class_name$::$method_name$($request_type$ request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(std::move(request));
}
`)
		} else if isStreamingRead(m) {
			p.PrintWith(mVars, `
StreamRange<$response_type$>
$client_class_name$::$method_name$($request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(request);
}
`)
		} else {
			p.PrintWith(mVars, `
$return_type$
$client_class_name$::$method_name$($request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->$method_name$(request);
}
`)
		}
	}

	for _, m := range asyncMethods {
		if isStreamingRead(m) || isStreamingWrite(m) {
			continue
		}
		mVars := buildMethodVars(svc, m, vars, lib, model)
		sigs := getValidSignatures(svc, m, lib)
		for _, s := range sigs {
			idxStr := strconv.Itoa(s.index)
			mVars["current_method_signature"] = mVars["method_signature"+idxStr]
			mVars["current_request_setters"] = mVars["method_request_setters"+idxStr]
			p.PrintWith(mVars, `
future<$return_type$>
$client_class_name$::Async$method_name$($current_method_signature$Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  $request_type$ request;
$current_request_setters$  return connection_->Async$method_name$(request);
}
`)
		}

		p.PrintWith(mVars, `
future<$return_type$>
$client_class_name$::Async$method_name$($request_type$ const& request, Options opts) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), options_));
  return connection_->Async$method_name$(request);
}
`)
	}

	p.HeaderCloseNamespaces(vars["product_namespace"])

	return filepath.Clean(ccPath), p.String()
}
