// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/googleapis/librarian/internal/config"
)

func TestClean(t *testing.T) {
	tempDir := t.TempDir()
	outDir := filepath.Join(tempDir, "google/cloud/test/v1")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		t.Fatal(err)
	}

	genFile := filepath.Join(outDir, "test_client.cc")
	licensePreamble := `// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

`
	genContent := licensePreamble + "// Generated by the Codegen C++ plugin.\n// Rest of file\n"
	if err := os.WriteFile(genFile, []byte(genContent), 0644); err != nil {
		t.Fatal(err)
	}

	handwrittenFile := filepath.Join(outDir, "CMakeLists.txt")
	handwrittenContent := "# Handwritten build file\n"
	if err := os.WriteFile(handwrittenFile, []byte(handwrittenContent), 0644); err != nil {
		t.Fatal(err)
	}

	keptFile := filepath.Join(outDir, "custom.cc")
	keptContent := "// Generated by the Codegen C++ plugin.\n// Kept file\n"
	if err := os.WriteFile(keptFile, []byte(keptContent), 0644); err != nil {
		t.Fatal(err)
	}

	lib := &config.Library{
		Output: outDir,
		Keep:   []string{"custom.cc"},
	}

	if err := Clean(lib); err != nil {
		t.Fatalf("Clean failed: %v", err)
	}

	if _, err := os.Stat(genFile); !os.IsNotExist(err) {
		t.Errorf("expected generated file %s to be removed", genFile)
	}
	if _, err := os.Stat(handwrittenFile); err != nil {
		t.Errorf("expected handwritten file %s to be preserved: %v", handwrittenFile, err)
	}
	if _, err := os.Stat(keptFile); err != nil {
		t.Errorf("expected kept file %s to be preserved: %v", keptFile, err)
	}
}
