// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cpp

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
)

var generatedMarker = []byte("Generated by the Codegen C++ plugin")

// Clean removes generated files in the library output directory.
// Handwritten files (such as CMakeLists.txt, BUILD.bazel, README.md, samples, docs) are preserved.
func Clean(library *config.Library) error {
	outdirs := make(map[string]struct{})
	if library.Output != "" {
		outdirs[library.Output] = struct{}{}
	}
	if library.Cpp != nil {
		if library.Cpp.ProductPath != "" {
			outdirs[library.Cpp.ProductPath] = struct{}{}
		}
		if library.Cpp.ForwardingProductPath != "" {
			outdirs[library.Cpp.ForwardingProductPath] = struct{}{}
		}
	}
	if len(outdirs) == 0 {
		return nil
	}

	keepSet := make(map[string]bool)
	for _, k := range library.Keep {
		keepSet[filepath.Clean(k)] = true
	}

	for dir := range outdirs {
		err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if d.Name() == "samples" {
					return filepath.SkipDir
				}
				return nil
			}
			if strings.HasSuffix(path, "_proto_export.h") {
				return nil
			}
			rel, err := filepath.Rel(dir, path)
			if err != nil {
				return err
			}
			if keepSet[filepath.Clean(rel)] {
				return nil
			}

			f, err := os.Open(path)
			if err != nil {
				return err
			}
			buf := make([]byte, 2048)
			n, _ := f.Read(buf)
			_ = f.Close()

			if bytes.Contains(buf[:n], generatedMarker) {
				return os.Remove(path)
			}
			return nil
		})
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	return nil
}
